/**
 * This class is generated by jOOQ
 */
package org.jooq.test.hsqldb.generatedclasses.procedures;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.SQLDialect;
import org.jooq.impl.ParameterImpl;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.StoredProcedureImpl;
import org.jooq.test.hsqldb.generatedclasses.Public;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class PArrays1 extends StoredProcedureImpl {

	private static final long serialVersionUID = -318524024;


	/**
	 * An uncommented item
	 */
	public static final Parameter<Integer[]> IN_ARRAY = new ParameterImpl<Integer[]>("IN_ARRAY", SQLDataType.INTEGER.getArrayDataType());

	/**
	 * An uncommented item
	 */
	public static final Parameter<Integer[]> OUT_ARRAY = new ParameterImpl<Integer[]>("OUT_ARRAY", SQLDataType.INTEGER.getArrayDataType());

	/**
	 * Create a new procedure call instance
	 */
	public PArrays1() {
		super(SQLDialect.HSQLDB, "P_ARRAYS1", Public.PUBLIC);

		addInParameter(IN_ARRAY);
		addOutParameter(OUT_ARRAY);
	}

	public void setInArray(Integer[] value) {
		setValue(IN_ARRAY, value);
	}

	public Integer[] getOutArray() {
		return getValue(OUT_ARRAY);
	}
}
