/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.information_schema;

import java.lang.String;
import org.jooq.Field;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class GlobalVariables extends TableImpl {

	/**
	 * The singleton instance of GLOBAL_VARIABLES
	 */
	public static final GlobalVariables GLOBAL_VARIABLES = new GlobalVariables();

	/**
	 * An uncommented column
	 */
	public static final Field<String> VARIABLE_NAME = new TableFieldImpl<String>("VARIABLE_NAME", String.class, GLOBAL_VARIABLES);

	/**
	 * An uncommented column
	 */
	public static final Field<String> VARIABLE_VALUE = new TableFieldImpl<String>("VARIABLE_VALUE", String.class, GLOBAL_VARIABLES);

	/**
	 * No further instances allowed
	 */
	private GlobalVariables() {
		super("GLOBAL_VARIABLES", "information_schema");
	}
}
