/**
 * This class is generated by jOOQ
 */
package org.jooq.util.oracle.sys.tables.records;


import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.TableRecordImpl;
import org.jooq.util.oracle.sys.tables.AllColComments;


/**
 * This class is generated by jOOQ.
 *
 * Comments on columns of accessible tables and views
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class AllColCommentsRecord extends TableRecordImpl<AllColCommentsRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Owner of the object
	 */
	public void setOwner(String value) {
		setValue(AllColComments.OWNER, value);
	}

	/**
	 * Owner of the object
	 */
	public String getOwner() {
		return getValue(AllColComments.OWNER);
	}

	/**
	 * Name of the object
	 */
	public void setTableName(String value) {
		setValue(AllColComments.TABLE_NAME, value);
	}

	/**
	 * Name of the object
	 */
	public String getTableName() {
		return getValue(AllColComments.TABLE_NAME);
	}

	/**
	 * Name of the column
	 */
	public void setColumnName(String value) {
		setValue(AllColComments.COLUMN_NAME, value);
	}

	/**
	 * Name of the column
	 */
	public String getColumnName() {
		return getValue(AllColComments.COLUMN_NAME);
	}

	/**
	 * Comment on the column
	 */
	public void setComments(String value) {
		setValue(AllColComments.COMMENTS, value);
	}

	/**
	 * Comment on the column
	 */
	public String getComments() {
		return getValue(AllColComments.COMMENTS);
	}

	public AllColCommentsRecord(Configuration configuration) {
		super(configuration, AllColComments.ALL_COL_COMMENTS);
	}
}
