/**
 * This class is generated by jOOQ
 */
package org.jooq.util.oracle.sys.tables.records;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.TableRecordImpl;
import org.jooq.util.oracle.sys.tables.AllObjects;


/**
 * This class is generated by jOOQ.
 *
 * Objects accessible to the user
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class AllObjectsRecord extends TableRecordImpl<AllObjectsRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Username of the owner of the object
	 */
	public void setOwner(String value) {
		setValue(AllObjects.OWNER, value);
	}

	/**
	 * Username of the owner of the object
	 */
	public String getOwner() {
		return getValue(AllObjects.OWNER);
	}

	/**
	 * Name of the object
	 */
	public void setObjectName(String value) {
		setValue(AllObjects.OBJECT_NAME, value);
	}

	/**
	 * Name of the object
	 */
	public String getObjectName() {
		return getValue(AllObjects.OBJECT_NAME);
	}

	/**
	 * Name of the sub-object (for example, partititon)
	 */
	public void setSubobjectName(String value) {
		setValue(AllObjects.SUBOBJECT_NAME, value);
	}

	/**
	 * Name of the sub-object (for example, partititon)
	 */
	public String getSubobjectName() {
		return getValue(AllObjects.SUBOBJECT_NAME);
	}

	/**
	 * Object number of the object
	 */
	public void setObjectId(BigDecimal value) {
		setValue(AllObjects.OBJECT_ID, value);
	}

	/**
	 * Object number of the object
	 */
	public BigDecimal getObjectId() {
		return getValue(AllObjects.OBJECT_ID);
	}

	/**
	 * Object number of the segment which contains the object
	 */
	public void setDataObjectId(BigDecimal value) {
		setValue(AllObjects.DATA_OBJECT_ID, value);
	}

	/**
	 * Object number of the segment which contains the object
	 */
	public BigDecimal getDataObjectId() {
		return getValue(AllObjects.DATA_OBJECT_ID);
	}

	/**
	 * Type of the object
	 */
	public void setObjectType(String value) {
		setValue(AllObjects.OBJECT_TYPE, value);
	}

	/**
	 * Type of the object
	 */
	public String getObjectType() {
		return getValue(AllObjects.OBJECT_TYPE);
	}

	/**
	 * Timestamp for the creation of the object
	 */
	public void setCreated(Date value) {
		setValue(AllObjects.CREATED, value);
	}

	/**
	 * Timestamp for the creation of the object
	 */
	public Date getCreated() {
		return getValue(AllObjects.CREATED);
	}

	/**
	 * Timestamp for the last DDL change (including GRANT and REVOKE) to the object
	 */
	public void setLastDdlTime(Date value) {
		setValue(AllObjects.LAST_DDL_TIME, value);
	}

	/**
	 * Timestamp for the last DDL change (including GRANT and REVOKE) to the object
	 */
	public Date getLastDdlTime() {
		return getValue(AllObjects.LAST_DDL_TIME);
	}

	/**
	 * Timestamp for the specification of the object
	 */
	public void setTimestamp(String value) {
		setValue(AllObjects.TIMESTAMP, value);
	}

	/**
	 * Timestamp for the specification of the object
	 */
	public String getTimestamp() {
		return getValue(AllObjects.TIMESTAMP);
	}

	/**
	 * Status of the object
	 */
	public void setStatus(String value) {
		setValue(AllObjects.STATUS, value);
	}

	/**
	 * Status of the object
	 */
	public String getStatus() {
		return getValue(AllObjects.STATUS);
	}

	/**
	 * Can the current session only see data that it placed in this object itself?
	 */
	public void setTemporary(String value) {
		setValue(AllObjects.TEMPORARY, value);
	}

	/**
	 * Can the current session only see data that it placed in this object itself?
	 */
	public String getTemporary() {
		return getValue(AllObjects.TEMPORARY);
	}

	/**
	 * Was the name of this object system generated?
	 */
	public void setGenerated(String value) {
		setValue(AllObjects.GENERATED, value);
	}

	/**
	 * Was the name of this object system generated?
	 */
	public String getGenerated() {
		return getValue(AllObjects.GENERATED);
	}

	/**
	 * Is this a secondary object created as part of icreate for domain indexes?
	 */
	public void setSecondary(String value) {
		setValue(AllObjects.SECONDARY, value);
	}

	/**
	 * Is this a secondary object created as part of icreate for domain indexes?
	 */
	public String getSecondary() {
		return getValue(AllObjects.SECONDARY);
	}

	public AllObjectsRecord(Configuration configuration) {
		super(configuration, AllObjects.ALL_OBJECTS);
	}
}
