/**
 * This class is generated by jOOQ
 */
package org.jooq.util.postgres.information_schema;


import javax.annotation.Generated;

import org.jooq.SQLDialect;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class InformationSchema extends SchemaImpl {

	private static final long serialVersionUID = -1948993289;

	/**
	 * The singleton instance of information_schema
	 */
	public static final InformationSchema INFORMATION_SCHEMA = new InformationSchema();

	/**
	 * No further instances allowed
	 */
	private InformationSchema() {
		super(SQLDialect.POSTGRES, "information_schema");
	}
}
