/**
 * This class is generated by jOOQ
 */
package org.jooq.test.h2.generatedclasses.functions;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.SQLDialect;
import org.jooq.Select;
import org.jooq.impl.ParameterImpl;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.StoredFunctionImpl;
import org.jooq.test.h2.generatedclasses.Public;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class FNumber extends StoredFunctionImpl<Integer> {

	private static final long serialVersionUID = -1811604258;


	/**
	 * An uncommented item
	 */
	public static final Parameter<Integer> P1 = new ParameterImpl<Integer>("P1", SQLDataType.INTEGER);

	/**
	 * Create a new function call instance
	 */
	public FNumber() {
		super(SQLDialect.H2, "F_NUMBER", Public.PUBLIC, SQLDataType.INTEGER);

		addInParameter(P1);
	}

	/**
	 * Set the <code>P1</code> parameter to the function
	 */
	public void setP1(Integer value) {
		setValue(P1, value);
	}

	/**
	 * Set the <code>P1</code> parameter to the function
	 * <p>
	 * Use this method only, if the function is called as a {@link Field} in a {@link Select} statement!
	 */
	public void setP1(Field<Integer> field) {
		setField(P1, field);
	}
}
