/**
 * This class is generated by jOOQ
 */
package org.jooq.test.sqlserver.generatedclasses.procedures;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.SQLDialect;
import org.jooq.impl.ParameterImpl;
import org.jooq.impl.StoredProcedureImpl;
import org.jooq.test.sqlserver.generatedclasses.Dbo;
import org.jooq.util.sqlserver.SQLServerDataType;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class PCreateAuthorByName extends StoredProcedureImpl {

	private static final long serialVersionUID = -583144038;


	/**
	 * An uncommented item
	 */
	public static final Parameter<String> FIRST_NAME = new ParameterImpl<String>(SQLDialect.SQLSERVER, "first_name", SQLServerDataType.VARCHAR);

	/**
	 * An uncommented item
	 */
	public static final Parameter<String> LAST_NAME = new ParameterImpl<String>(SQLDialect.SQLSERVER, "last_name", SQLServerDataType.VARCHAR);

	/**
	 * No further instances allowed
	 */
	public PCreateAuthorByName() {
		super(SQLDialect.SQLSERVER, "p_create_author_by_name", Dbo.DBO);

		addInParameter(FIRST_NAME);
		addInParameter(LAST_NAME);
	}

	public void setFirstName(String value) {
		setValue(FIRST_NAME, value);
	}

	public void setLastName(String value) {
		setValue(LAST_NAME, value);
	}
}
