/**
 * This class is generated by jOOQ
 */
package org.jooq.test.sqlserver.generatedclasses.procedures;


import javax.annotation.Generated;

import org.jooq.SQLDialect;
import org.jooq.impl.StoredProcedureImpl;
import org.jooq.test.sqlserver.generatedclasses.Dbo;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class PCreateAuthor extends StoredProcedureImpl {

	private static final long serialVersionUID = 1446657985;


	/**
	 * No further instances allowed
	 */
	public PCreateAuthor() {
		super(SQLDialect.SQLSERVER, "p_create_author", Dbo.DBO);
	}
}
