/**
 * This class is generated by jOOQ
 */
package org.jooq.util.sybase.sys.tables.records;


import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.TableRecordImpl;
import org.jooq.util.sybase.sys.tables.Systabcol;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class SystabcolRecord extends TableRecordImpl<SystabcolRecord> {

	private static final long serialVersionUID = -1879265146;

	/**
	 * An uncommented item
	 */
	public void setTableId(Integer value) {
		setValue(Systabcol.TABLE_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableId() {
		return getValue(Systabcol.TABLE_ID);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnId(Integer value) {
		setValue(Systabcol.COLUMN_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getColumnId() {
		return getValue(Systabcol.COLUMN_ID);
	}

	/**
	 * An uncommented item
	 */
	public void setDomainId(Short value) {
		setValue(Systabcol.DOMAIN_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public Short getDomainId() {
		return getValue(Systabcol.DOMAIN_ID);
	}

	/**
	 * An uncommented item
	 */
	public void setNulls(String value) {
		setValue(Systabcol.NULLS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getNulls() {
		return getValue(Systabcol.NULLS);
	}

	/**
	 * An uncommented item
	 */
	public void setWidth(Long value) {
		setValue(Systabcol.WIDTH, value);
	}

	/**
	 * An uncommented item
	 */
	public Long getWidth() {
		return getValue(Systabcol.WIDTH);
	}

	/**
	 * An uncommented item
	 */
	public void setScale(Short value) {
		setValue(Systabcol.SCALE, value);
	}

	/**
	 * An uncommented item
	 */
	public Short getScale() {
		return getValue(Systabcol.SCALE);
	}

	/**
	 * An uncommented item
	 */
	public void setObjectId(Long value) {
		setValue(Systabcol.OBJECT_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public Long getObjectId() {
		return getValue(Systabcol.OBJECT_ID);
	}

	/**
	 * An uncommented item
	 */
	public void setMaxIdentity(Long value) {
		setValue(Systabcol.MAX_IDENTITY, value);
	}

	/**
	 * An uncommented item
	 */
	public Long getMaxIdentity() {
		return getValue(Systabcol.MAX_IDENTITY);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnName(String value) {
		setValue(Systabcol.COLUMN_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnName() {
		return getValue(Systabcol.COLUMN_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setDefault(String value) {
		setValue(Systabcol.DEFAULT, value);
	}

	/**
	 * An uncommented item
	 */
	public String getDefault() {
		return getValue(Systabcol.DEFAULT);
	}

	/**
	 * An uncommented item
	 */
	public void setUserType(Short value) {
		setValue(Systabcol.USER_TYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public Short getUserType() {
		return getValue(Systabcol.USER_TYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnType(String value) {
		setValue(Systabcol.COLUMN_TYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnType() {
		return getValue(Systabcol.COLUMN_TYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setCompressed(Byte value) {
		setValue(Systabcol.COMPRESSED, value);
	}

	/**
	 * An uncommented item
	 */
	public Byte getCompressed() {
		return getValue(Systabcol.COMPRESSED);
	}

	/**
	 * An uncommented item
	 */
	public void setCollectStats(Byte value) {
		setValue(Systabcol.COLLECT_STATS, value);
	}

	/**
	 * An uncommented item
	 */
	public Byte getCollectStats() {
		return getValue(Systabcol.COLLECT_STATS);
	}

	/**
	 * An uncommented item
	 */
	public void setInlineMax(Short value) {
		setValue(Systabcol.INLINE_MAX, value);
	}

	/**
	 * An uncommented item
	 */
	public Short getInlineMax() {
		return getValue(Systabcol.INLINE_MAX);
	}

	/**
	 * An uncommented item
	 */
	public void setInlineLong(Short value) {
		setValue(Systabcol.INLINE_LONG, value);
	}

	/**
	 * An uncommented item
	 */
	public Short getInlineLong() {
		return getValue(Systabcol.INLINE_LONG);
	}

	/**
	 * An uncommented item
	 */
	public void setLobIndex(Byte value) {
		setValue(Systabcol.LOB_INDEX, value);
	}

	/**
	 * An uncommented item
	 */
	public Byte getLobIndex() {
		return getValue(Systabcol.LOB_INDEX);
	}

	/**
	 * An uncommented item
	 */
	public void setBaseTypeStr(String value) {
		setValue(Systabcol.BASE_TYPE_STR, value);
	}

	/**
	 * An uncommented item
	 */
	public String getBaseTypeStr() {
		return getValue(Systabcol.BASE_TYPE_STR);
	}
	/**
	 * Create a detached SystabcolRecord
	 */
	public SystabcolRecord() {
		super(Systabcol.SYSTABCOL);
	}

	/**
	 * Create an attached SystabcolRecord
	 * @deprecated - (#363) use the other constructor instead
	 */
	@Deprecated
	public SystabcolRecord(Configuration configuration) {
		super(Systabcol.SYSTABCOL, configuration);
	}
}
