/**
 * This class is generated by jOOQ
 */
package org.jooq.test.hsqldb.generatedclasses.tables;


import javax.annotation.Generated;

import org.jooq.SQLDialect;
import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.test.hsqldb.generatedclasses.Public;
import org.jooq.test.hsqldb.generatedclasses.tables.records.VBookRecord;
import org.jooq.util.hsqldb.HSQLDBDataType;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class VBook extends TableImpl<VBookRecord> {

	private static final long serialVersionUID = -1335204627;

	/**
	 * The singleton instance of V_BOOK
	 */
	public static final VBook V_BOOK = new VBook();

	/**
	 * The class holding records for this type
	 */
	private static final Class<VBookRecord> __RECORD_TYPE = VBookRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<VBookRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, Integer> ID = new TableFieldImpl<VBookRecord, Integer>(SQLDialect.HSQLDB, "ID", HSQLDBDataType.INTEGER, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, Integer> AUTHOR_ID = new TableFieldImpl<VBookRecord, Integer>(SQLDialect.HSQLDB, "AUTHOR_ID", HSQLDBDataType.INTEGER, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, Integer> CO_AUTHOR_ID = new TableFieldImpl<VBookRecord, Integer>(SQLDialect.HSQLDB, "CO_AUTHOR_ID", HSQLDBDataType.INTEGER, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, Integer> DETAILS_ID = new TableFieldImpl<VBookRecord, Integer>(SQLDialect.HSQLDB, "DETAILS_ID", HSQLDBDataType.INTEGER, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, String> TITLE = new TableFieldImpl<VBookRecord, String>(SQLDialect.HSQLDB, "TITLE", HSQLDBDataType.CHARACTERVARYING, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, Integer> PUBLISHED_IN = new TableFieldImpl<VBookRecord, Integer>(SQLDialect.HSQLDB, "PUBLISHED_IN", HSQLDBDataType.INTEGER, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, Integer> LANGUAGE_ID = new TableFieldImpl<VBookRecord, Integer>(SQLDialect.HSQLDB, "LANGUAGE_ID", HSQLDBDataType.INTEGER, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, String> CONTENT_TEXT = new TableFieldImpl<VBookRecord, String>(SQLDialect.HSQLDB, "CONTENT_TEXT", HSQLDBDataType.CHARACTERLARGEOBJECT, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, byte[]> CONTENT_PDF = new TableFieldImpl<VBookRecord, byte[]>(SQLDialect.HSQLDB, "CONTENT_PDF", HSQLDBDataType.BINARYLARGEOBJECT, V_BOOK);

	/**
	 * No further instances allowed
	 */
	private VBook() {
		super(SQLDialect.HSQLDB, "V_BOOK", Public.PUBLIC);
	}
}
