/**
 * This class is generated by jOOQ
 */
package org.jooq.test.hsqldb.generatedclasses.tables;


import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.UpdatableTableImpl;
import org.jooq.test.hsqldb.generatedclasses.Public;
import org.jooq.test.hsqldb.generatedclasses.tables.records.XUnusedRecord;


/**
 * This class is generated by jOOQ.
 */
public class XUnused extends UpdatableTableImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * The singleton instance of X_UNUSED
	 */
	public static final XUnused X_UNUSED = new XUnused();

	/**
	 * The class holding records for this table
	 */
	private static final Class<XUnusedRecord> RECORD_TYPE = XUnusedRecord.class;

	/**
	 * The class holding records for this table
	 */
	@Override
	public Class<XUnusedRecord> getRecordType() {
		return RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY 'SYS_PK_11613'
	 */
	public static final TableField<Integer> ID = new TableFieldImpl<Integer>("ID", Integer.class, X_UNUSED);

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY 'SYS_PK_11613'
	 */
	public static final TableField<String> NAME = new TableFieldImpl<String>("NAME", String.class, X_UNUSED);

	/**
	 * An uncommented item
	 * 
	 * FOREIGN KEY 'SYS_FK_11614' [NAME_REF, ID_REF] REFERENCES X_UNUSED [NAME, ID]
	 */
	public static final TableField<Integer> ID_REF = new TableFieldImpl<Integer>("ID_REF", Integer.class, X_UNUSED);

	/**
	 * An uncommented item
	 * 
	 * FOREIGN KEY 'SYS_FK_11614' [NAME_REF, ID_REF] REFERENCES X_UNUSED [NAME, ID]
	 */
	public static final TableField<String> NAME_REF = new TableFieldImpl<String>("NAME_REF", String.class, X_UNUSED);

	/**
	 * No further instances allowed
	 */
	private XUnused() {
		super("X_UNUSED", Public.PUBLIC);
	}

	/*
	 * static initialiser
	 */
	static {
		X_UNUSED.addToPrimaryKey(NAME);
		X_UNUSED.addToPrimaryKey(ID);
	}

}
