/**
 * This class is generated by jOOQ
 */
package org.jooq.util.postgres.pg_catalog.tables.records;


import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.TableRecordImpl;
import org.jooq.util.postgres.pg_catalog.tables.PgType;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class PgTypeRecord extends TableRecordImpl<PgTypeRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public void setTypname(Object value) {
		setValue(PgType.TYPNAME, value);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public Object getTypname() {
		return getValue(PgType.TYPNAME);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public void setTypnamespace(Object value) {
		setValue(PgType.TYPNAMESPACE, value);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public Object getTypnamespace() {
		return getValue(PgType.TYPNAMESPACE);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public void setTypowner(Object value) {
		setValue(PgType.TYPOWNER, value);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public Object getTypowner() {
		return getValue(PgType.TYPOWNER);
	}

	/**
	 * An uncommented item
	 */
	public void setTyplen(Short value) {
		setValue(PgType.TYPLEN, value);
	}

	/**
	 * An uncommented item
	 */
	public Short getTyplen() {
		return getValue(PgType.TYPLEN);
	}

	/**
	 * An uncommented item
	 */
	public void setTypbyval(Boolean value) {
		setValue(PgType.TYPBYVAL, value);
	}

	/**
	 * An uncommented item
	 */
	public Boolean getTypbyval() {
		return getValue(PgType.TYPBYVAL);
	}

	/**
	 * An uncommented item
	 */
	public void setTyptype(String value) {
		setValue(PgType.TYPTYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTyptype() {
		return getValue(PgType.TYPTYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setTypcategory(String value) {
		setValue(PgType.TYPCATEGORY, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTypcategory() {
		return getValue(PgType.TYPCATEGORY);
	}

	/**
	 * An uncommented item
	 */
	public void setTypispreferred(Boolean value) {
		setValue(PgType.TYPISPREFERRED, value);
	}

	/**
	 * An uncommented item
	 */
	public Boolean getTypispreferred() {
		return getValue(PgType.TYPISPREFERRED);
	}

	/**
	 * An uncommented item
	 */
	public void setTypisdefined(Boolean value) {
		setValue(PgType.TYPISDEFINED, value);
	}

	/**
	 * An uncommented item
	 */
	public Boolean getTypisdefined() {
		return getValue(PgType.TYPISDEFINED);
	}

	/**
	 * An uncommented item
	 */
	public void setTypdelim(String value) {
		setValue(PgType.TYPDELIM, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTypdelim() {
		return getValue(PgType.TYPDELIM);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public void setTyprelid(Object value) {
		setValue(PgType.TYPRELID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public Object getTyprelid() {
		return getValue(PgType.TYPRELID);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public void setTypelem(Object value) {
		setValue(PgType.TYPELEM, value);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public Object getTypelem() {
		return getValue(PgType.TYPELEM);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public void setTyparray(Object value) {
		setValue(PgType.TYPARRAY, value);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public Object getTyparray() {
		return getValue(PgType.TYPARRAY);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public void setTypinput(Object value) {
		setValue(PgType.TYPINPUT, value);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public Object getTypinput() {
		return getValue(PgType.TYPINPUT);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public void setTypoutput(Object value) {
		setValue(PgType.TYPOUTPUT, value);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public Object getTypoutput() {
		return getValue(PgType.TYPOUTPUT);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public void setTypreceive(Object value) {
		setValue(PgType.TYPRECEIVE, value);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public Object getTypreceive() {
		return getValue(PgType.TYPRECEIVE);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public void setTypsend(Object value) {
		setValue(PgType.TYPSEND, value);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public Object getTypsend() {
		return getValue(PgType.TYPSEND);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public void setTypmodin(Object value) {
		setValue(PgType.TYPMODIN, value);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public Object getTypmodin() {
		return getValue(PgType.TYPMODIN);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public void setTypmodout(Object value) {
		setValue(PgType.TYPMODOUT, value);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public Object getTypmodout() {
		return getValue(PgType.TYPMODOUT);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public void setTypanalyze(Object value) {
		setValue(PgType.TYPANALYZE, value);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public Object getTypanalyze() {
		return getValue(PgType.TYPANALYZE);
	}

	/**
	 * An uncommented item
	 */
	public void setTypalign(String value) {
		setValue(PgType.TYPALIGN, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTypalign() {
		return getValue(PgType.TYPALIGN);
	}

	/**
	 * An uncommented item
	 */
	public void setTypstorage(String value) {
		setValue(PgType.TYPSTORAGE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTypstorage() {
		return getValue(PgType.TYPSTORAGE);
	}

	/**
	 * An uncommented item
	 */
	public void setTypnotnull(Boolean value) {
		setValue(PgType.TYPNOTNULL, value);
	}

	/**
	 * An uncommented item
	 */
	public Boolean getTypnotnull() {
		return getValue(PgType.TYPNOTNULL);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public void setTypbasetype(Object value) {
		setValue(PgType.TYPBASETYPE, value);
	}

	/**
	 * An uncommented item
	 * 
	 * The SQL type of this item could not be mapped. Deserialising this field might not work!
	 */
	public Object getTypbasetype() {
		return getValue(PgType.TYPBASETYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setTyptypmod(Integer value) {
		setValue(PgType.TYPTYPMOD, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTyptypmod() {
		return getValue(PgType.TYPTYPMOD);
	}

	/**
	 * An uncommented item
	 */
	public void setTypndims(Integer value) {
		setValue(PgType.TYPNDIMS, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTypndims() {
		return getValue(PgType.TYPNDIMS);
	}

	/**
	 * An uncommented item
	 */
	public void setTypdefaultbin(String value) {
		setValue(PgType.TYPDEFAULTBIN, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTypdefaultbin() {
		return getValue(PgType.TYPDEFAULTBIN);
	}

	/**
	 * An uncommented item
	 */
	public void setTypdefault(String value) {
		setValue(PgType.TYPDEFAULT, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTypdefault() {
		return getValue(PgType.TYPDEFAULT);
	}

	public PgTypeRecord(Configuration configuration) {
		super(configuration, PgType.PG_TYPE);
	}
}
