DROP VIEW IF EXISTS v_library;
/
DROP TABLE IF EXISTS t_book_to_book_store;
/
DROP TABLE IF EXISTS t_book_store;
/
DROP TABLE IF EXISTS t_book;
/
DROP TABLE IF EXISTS t_book_details;
/
DROP TABLE IF EXISTS t_author;
/
DROP TABLE IF EXISTS t_language;
/
DROP TABLE IF EXISTS x_test_case_71;
/
DROP TABLE IF EXISTS x_test_case_64_69;
/
DROP TABLE IF EXISTS x_test_case_85;
/
DROP TABLE IF EXISTS x_unused;
/

CREATE TABLE t_language (
  id INTEGER NOT NULL PRIMARY KEY,
  cd CHAR(2) NOT NULL,
  description VARCHAR(50)
);
/

CREATE TABLE t_author (
	ID INT NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50) NOT NULL,
	DATE_OF_BIRTH DATE,
	YEAR_OF_BIRTH INT,
	ADDRESS VARCHAR(50)
);
/

CREATE TABLE t_book_details (
    ID INT PRIMARY KEY
);
/

CREATE TABLE t_book (
	ID INT NOT NULL PRIMARY KEY,
	AUTHOR_ID INT NOT NULL,
	co_author_id INTEGER,
	DETAILS_ID INT,
	TITLE VARCHAR(400) NOT NULL,
	PUBLISHED_IN INT NOT NULL,
	LANGUAGE_ID INT NOT NULL,
	CONTENT_TEXT LONGVARCHAR,
	CONTENT_PDF LONGVARBINARY,
	FOREIGN KEY (AUTHOR_ID) REFERENCES T_AUTHOR(ID),
	FOREIGN KEY (CO_AUTHOR_ID) REFERENCES T_AUTHOR(ID),
	FOREIGN KEY (DETAILS_ID) REFERENCES T_BOOK_DETAILS(ID),
	FOREIGN KEY (LANGUAGE_ID) REFERENCES T_LANGUAGE(ID)
);
/

CREATE TABLE t_book_store (
  name VARCHAR(400) NOT NULL PRIMARY KEY
);
/

CREATE TABLE t_book_to_book_store (
  book_store_name VARCHAR(400) NOT NULL,
  book_id INT NOT NULL,
  stock INT,
  PRIMARY KEY(book_store_name, book_id),
  CONSTRAINT b2bs_book_store_id
    FOREIGN KEY (book_store_name)
    REFERENCES t_book_store (name)
    ON DELETE CASCADE,
  CONSTRAINT b2bs_book_id
    FOREIGN KEY (book_id)
    REFERENCES t_book (id)
    ON DELETE CASCADE
)
/


CREATE TABLE x_unused (
	ID INT NOT NULL UNIQUE,
	NAME VARCHAR(10) NOT NULL,
	ID_REF INT,
	CLASS INT,
	FIELDS INT,
	CONFIGURATION INT,
	U_D_T INT,
	META_DATA INT,
	TYPE0 INT,
	PRIMARY_KEY INT,
	PRIMARYKEY INT,	
	NAME_REF VARCHAR(10),
	PRIMARY KEY(ID, NAME),
	FOREIGN KEY(ID_REF, NAME_REF) REFERENCES X_UNUSED(ID, NAME)
);
/

CREATE TABLE x_test_case_64_69 (
    ID INT NOT NULL,
    UNUSED_ID INT,
    PRIMARY KEY(ID),
    FOREIGN KEY(UNUSED_ID) REFERENCES X_UNUSED(ID)
);
/

CREATE TABLE x_test_case_71 (
	ID INT NOT NULL,
	TEST_CASE_64_69_ID SMALLINT,
	PRIMARY KEY(ID),
	FOREIGN KEY(TEST_CASE_64_69_ID) REFERENCES X_TEST_CASE_64_69(ID)
);
/

CREATE TABLE x_test_case_85 (
	id int NOT NULL,
	x_unused_id int,
	x_unused_name VARCHAR(10),
	PRIMARY KEY(ID),
	FOREIGN KEY(x_unused_id, x_unused_name) REFERENCES X_UNUSED(id, name)
);
/

CREATE VIEW V_LIBRARY AS
SELECT T_AUTHOR.FIRST_NAME AUTHOR, T_BOOK.TITLE TITLE
FROM T_AUTHOR JOIN T_BOOK ON T_BOOK.AUTHOR_ID = T_AUTHOR.ID;
/
  

