/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.information_schema.tables;

import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.mysql.information_schema.InformationSchema;
import org.jooq.util.mysql.information_schema.tables.records.GlobalVariablesRecord;


/**
 * This class is generated by jOOQ.
 */
public class GlobalVariables extends TableImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * The singleton instance of GLOBAL_VARIABLES
	 */
	public static final GlobalVariables GLOBAL_VARIABLES = new GlobalVariables();

	/**
	 * The class holding records for this table
	 */
	private static final Class<GlobalVariablesRecord> RECORD_TYPE = GlobalVariablesRecord.class;

	/**
	 * The class holding records for this table
	 */
	@Override
	public Class<GlobalVariablesRecord> getRecordType() {
		return RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<String> VARIABLE_NAME = new TableFieldImpl<String>("VARIABLE_NAME", String.class, GLOBAL_VARIABLES);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> VARIABLE_VALUE = new TableFieldImpl<String>("VARIABLE_VALUE", String.class, GLOBAL_VARIABLES);

	/**
	 * No further instances allowed
	 */
	private GlobalVariables() {
		super("GLOBAL_VARIABLES", InformationSchema.INFORMATION_SCHEMA);
	}
}
