/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.information_schema.tables;

import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.mysql.information_schema.InformationSchema;
import org.jooq.util.mysql.information_schema.tables.records.PluginsRecord;


/**
 * This class is generated by jOOQ.
 */
public class Plugins extends TableImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * The singleton instance of PLUGINS
	 */
	public static final Plugins PLUGINS = new Plugins();

	/**
	 * The class holding records for this table
	 */
	private static final Class<PluginsRecord> RECORD_TYPE = PluginsRecord.class;

	/**
	 * The class holding records for this table
	 */
	@Override
	public Class<PluginsRecord> getRecordType() {
		return RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<String> PLUGIN_NAME = new TableFieldImpl<String>("PLUGIN_NAME", String.class, PLUGINS);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> PLUGIN_VERSION = new TableFieldImpl<String>("PLUGIN_VERSION", String.class, PLUGINS);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> PLUGIN_STATUS = new TableFieldImpl<String>("PLUGIN_STATUS", String.class, PLUGINS);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> PLUGIN_TYPE = new TableFieldImpl<String>("PLUGIN_TYPE", String.class, PLUGINS);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> PLUGIN_TYPE_VERSION = new TableFieldImpl<String>("PLUGIN_TYPE_VERSION", String.class, PLUGINS);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> PLUGIN_LIBRARY = new TableFieldImpl<String>("PLUGIN_LIBRARY", String.class, PLUGINS);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> PLUGIN_LIBRARY_VERSION = new TableFieldImpl<String>("PLUGIN_LIBRARY_VERSION", String.class, PLUGINS);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> PLUGIN_AUTHOR = new TableFieldImpl<String>("PLUGIN_AUTHOR", String.class, PLUGINS);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> PLUGIN_DESCRIPTION = new TableFieldImpl<String>("PLUGIN_DESCRIPTION", String.class, PLUGINS);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> PLUGIN_LICENSE = new TableFieldImpl<String>("PLUGIN_LICENSE", String.class, PLUGINS);

	/**
	 * No further instances allowed
	 */
	private Plugins() {
		super("PLUGINS", InformationSchema.INFORMATION_SCHEMA);
	}
}
