/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.information_schema.tables;

import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.mysql.information_schema.InformationSchema;
import org.jooq.util.mysql.information_schema.tables.records.TablePrivilegesRecord;


/**
 * This class is generated by jOOQ.
 */
public class TablePrivileges extends TableImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * The singleton instance of TABLE_PRIVILEGES
	 */
	public static final TablePrivileges TABLE_PRIVILEGES = new TablePrivileges();

	/**
	 * The class holding records for this table
	 */
	private static final Class<TablePrivilegesRecord> RECORD_TYPE = TablePrivilegesRecord.class;

	/**
	 * The class holding records for this table
	 */
	@Override
	public Class<TablePrivilegesRecord> getRecordType() {
		return RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<String> GRANTEE = new TableFieldImpl<String>("GRANTEE", String.class, TABLE_PRIVILEGES);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> TABLE_CATALOG = new TableFieldImpl<String>("TABLE_CATALOG", String.class, TABLE_PRIVILEGES);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> TABLE_SCHEMA = new TableFieldImpl<String>("TABLE_SCHEMA", String.class, TABLE_PRIVILEGES);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> TABLE_NAME = new TableFieldImpl<String>("TABLE_NAME", String.class, TABLE_PRIVILEGES);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> PRIVILEGE_TYPE = new TableFieldImpl<String>("PRIVILEGE_TYPE", String.class, TABLE_PRIVILEGES);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> IS_GRANTABLE = new TableFieldImpl<String>("IS_GRANTABLE", String.class, TABLE_PRIVILEGES);

	/**
	 * No further instances allowed
	 */
	private TablePrivileges() {
		super("TABLE_PRIVILEGES", InformationSchema.INFORMATION_SCHEMA);
	}
}
