/**
 * This class is generated by jOOQ
 */
package org.jooq.test.h2.generatedclasses.tables;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.SQLDialect;
import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.test.h2.generatedclasses.Public;
import org.jooq.test.h2.generatedclasses.tables.records.VAuthorRecord;
import org.jooq.util.h2.H2DataType;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class VAuthor extends TableImpl<VAuthorRecord> {

	private static final long serialVersionUID = 117016254;

	/**
	 * The singleton instance of V_AUTHOR
	 */
	public static final VAuthor V_AUTHOR = new VAuthor();

	/**
	 * The class holding records for this type
	 */
	private static final Class<VAuthorRecord> __RECORD_TYPE = VAuthorRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<VAuthorRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<VAuthorRecord, Integer> ID = new TableFieldImpl<VAuthorRecord, Integer>(SQLDialect.H2, "ID", H2DataType.INTEGER, V_AUTHOR);

	/**
	 * An uncommented item
	 */
	public static final TableField<VAuthorRecord, String> FIRST_NAME = new TableFieldImpl<VAuthorRecord, String>(SQLDialect.H2, "FIRST_NAME", H2DataType.VARCHAR, V_AUTHOR);

	/**
	 * An uncommented item
	 */
	public static final TableField<VAuthorRecord, String> LAST_NAME = new TableFieldImpl<VAuthorRecord, String>(SQLDialect.H2, "LAST_NAME", H2DataType.VARCHAR, V_AUTHOR);

	/**
	 * An uncommented item
	 */
	public static final TableField<VAuthorRecord, Date> DATE_OF_BIRTH = new TableFieldImpl<VAuthorRecord, Date>(SQLDialect.H2, "DATE_OF_BIRTH", H2DataType.DATE, V_AUTHOR);

	/**
	 * An uncommented item
	 */
	public static final TableField<VAuthorRecord, Integer> YEAR_OF_BIRTH = new TableFieldImpl<VAuthorRecord, Integer>(SQLDialect.H2, "YEAR_OF_BIRTH", H2DataType.INTEGER, V_AUTHOR);

	/**
	 * An uncommented item
	 */
	public static final TableField<VAuthorRecord, String> ADDRESS = new TableFieldImpl<VAuthorRecord, String>(SQLDialect.H2, "ADDRESS", H2DataType.VARCHAR, V_AUTHOR);

	/**
	 * No further instances allowed
	 */
	private VAuthor() {
		super(SQLDialect.H2, "V_AUTHOR", Public.PUBLIC);
	}
}
