/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.information_schema.tables.records;

import java.sql.Timestamp;
import org.jooq.Result;
import org.jooq.impl.RecordImpl;
import org.jooq.util.mysql.information_schema.tables.Files;


/**
 * This class is generated by jOOQ.
 */
public class FilesRecord extends RecordImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * An uncommented item
	 */
	public void setFileId(Integer value) {
		setValue(Files.FILE_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getFileId() {
		return getValue(Files.FILE_ID);
	}

	/**
	 * An uncommented item
	 */
	public void setFileName(String value) {
		setValue(Files.FILE_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getFileName() {
		return getValue(Files.FILE_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setFileType(String value) {
		setValue(Files.FILE_TYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getFileType() {
		return getValue(Files.FILE_TYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setTablespaceName(String value) {
		setValue(Files.TABLESPACE_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTablespaceName() {
		return getValue(Files.TABLESPACE_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setTableCatalog(String value) {
		setValue(Files.TABLE_CATALOG, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableCatalog() {
		return getValue(Files.TABLE_CATALOG);
	}

	/**
	 * An uncommented item
	 */
	public void setTableSchema(String value) {
		setValue(Files.TABLE_SCHEMA, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableSchema() {
		return getValue(Files.TABLE_SCHEMA);
	}

	/**
	 * An uncommented item
	 */
	public void setTableName(String value) {
		setValue(Files.TABLE_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableName() {
		return getValue(Files.TABLE_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setLogfileGroupName(String value) {
		setValue(Files.LOGFILE_GROUP_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getLogfileGroupName() {
		return getValue(Files.LOGFILE_GROUP_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setLogfileGroupNumber(Integer value) {
		setValue(Files.LOGFILE_GROUP_NUMBER, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getLogfileGroupNumber() {
		return getValue(Files.LOGFILE_GROUP_NUMBER);
	}

	/**
	 * An uncommented item
	 */
	public void setEngine(String value) {
		setValue(Files.ENGINE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getEngine() {
		return getValue(Files.ENGINE);
	}

	/**
	 * An uncommented item
	 */
	public void setFulltextKeys(String value) {
		setValue(Files.FULLTEXT_KEYS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getFulltextKeys() {
		return getValue(Files.FULLTEXT_KEYS);
	}

	/**
	 * An uncommented item
	 */
	public void setDeletedRows(Integer value) {
		setValue(Files.DELETED_ROWS, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getDeletedRows() {
		return getValue(Files.DELETED_ROWS);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateCount(Integer value) {
		setValue(Files.UPDATE_COUNT, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getUpdateCount() {
		return getValue(Files.UPDATE_COUNT);
	}

	/**
	 * An uncommented item
	 */
	public void setFreeExtents(Integer value) {
		setValue(Files.FREE_EXTENTS, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getFreeExtents() {
		return getValue(Files.FREE_EXTENTS);
	}

	/**
	 * An uncommented item
	 */
	public void setTotalExtents(Integer value) {
		setValue(Files.TOTAL_EXTENTS, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTotalExtents() {
		return getValue(Files.TOTAL_EXTENTS);
	}

	/**
	 * An uncommented item
	 */
	public void setExtentSize(Integer value) {
		setValue(Files.EXTENT_SIZE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getExtentSize() {
		return getValue(Files.EXTENT_SIZE);
	}

	/**
	 * An uncommented item
	 */
	public void setInitialSize(Integer value) {
		setValue(Files.INITIAL_SIZE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getInitialSize() {
		return getValue(Files.INITIAL_SIZE);
	}

	/**
	 * An uncommented item
	 */
	public void setMaximumSize(Integer value) {
		setValue(Files.MAXIMUM_SIZE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getMaximumSize() {
		return getValue(Files.MAXIMUM_SIZE);
	}

	/**
	 * An uncommented item
	 */
	public void setAutoextendSize(Integer value) {
		setValue(Files.AUTOEXTEND_SIZE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getAutoextendSize() {
		return getValue(Files.AUTOEXTEND_SIZE);
	}

	/**
	 * An uncommented item
	 */
	public void setCreationTime(Timestamp value) {
		setValue(Files.CREATION_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public Timestamp getCreationTime() {
		return getValue(Files.CREATION_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setLastUpdateTime(Timestamp value) {
		setValue(Files.LAST_UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public Timestamp getLastUpdateTime() {
		return getValue(Files.LAST_UPDATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setLastAccessTime(Timestamp value) {
		setValue(Files.LAST_ACCESS_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public Timestamp getLastAccessTime() {
		return getValue(Files.LAST_ACCESS_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setRecoverTime(Integer value) {
		setValue(Files.RECOVER_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getRecoverTime() {
		return getValue(Files.RECOVER_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setTransactionCounter(Integer value) {
		setValue(Files.TRANSACTION_COUNTER, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTransactionCounter() {
		return getValue(Files.TRANSACTION_COUNTER);
	}

	/**
	 * An uncommented item
	 */
	public void setVersion(Integer value) {
		setValue(Files.VERSION, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getVersion() {
		return getValue(Files.VERSION);
	}

	/**
	 * An uncommented item
	 */
	public void setRowFormat(String value) {
		setValue(Files.ROW_FORMAT, value);
	}

	/**
	 * An uncommented item
	 */
	public String getRowFormat() {
		return getValue(Files.ROW_FORMAT);
	}

	/**
	 * An uncommented item
	 */
	public void setTableRows(Integer value) {
		setValue(Files.TABLE_ROWS, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableRows() {
		return getValue(Files.TABLE_ROWS);
	}

	/**
	 * An uncommented item
	 */
	public void setAvgRowLength(Integer value) {
		setValue(Files.AVG_ROW_LENGTH, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getAvgRowLength() {
		return getValue(Files.AVG_ROW_LENGTH);
	}

	/**
	 * An uncommented item
	 */
	public void setDataLength(Integer value) {
		setValue(Files.DATA_LENGTH, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getDataLength() {
		return getValue(Files.DATA_LENGTH);
	}

	/**
	 * An uncommented item
	 */
	public void setMaxDataLength(Integer value) {
		setValue(Files.MAX_DATA_LENGTH, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getMaxDataLength() {
		return getValue(Files.MAX_DATA_LENGTH);
	}

	/**
	 * An uncommented item
	 */
	public void setIndexLength(Integer value) {
		setValue(Files.INDEX_LENGTH, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getIndexLength() {
		return getValue(Files.INDEX_LENGTH);
	}

	/**
	 * An uncommented item
	 */
	public void setDataFree(Integer value) {
		setValue(Files.DATA_FREE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getDataFree() {
		return getValue(Files.DATA_FREE);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(Timestamp value) {
		setValue(Files.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public Timestamp getCreateTime() {
		return getValue(Files.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(Timestamp value) {
		setValue(Files.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public Timestamp getUpdateTime() {
		return getValue(Files.UPDATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setCheckTime(Timestamp value) {
		setValue(Files.CHECK_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public Timestamp getCheckTime() {
		return getValue(Files.CHECK_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setChecksum(Integer value) {
		setValue(Files.CHECKSUM, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getChecksum() {
		return getValue(Files.CHECKSUM);
	}

	/**
	 * An uncommented item
	 */
	public void setStatus(String value) {
		setValue(Files.STATUS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getStatus() {
		return getValue(Files.STATUS);
	}

	/**
	 * An uncommented item
	 */
	public void setExtra(String value) {
		setValue(Files.EXTRA, value);
	}

	/**
	 * An uncommented item
	 */
	public String getExtra() {
		return getValue(Files.EXTRA);
	}

	public FilesRecord(Result result) {
		super(result);
	}
}
