/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.information_schema.tables;

import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.mysql.information_schema.InformationSchema;


/**
 * This class is generated by jOOQ.
 */
public class ColumnPrivileges extends TableImpl {

	private static final long serialVersionUID = -3153667983818760353L;

	/**
	 * The singleton instance of COLUMN_PRIVILEGES
	 */
	public static final ColumnPrivileges COLUMN_PRIVILEGES = new ColumnPrivileges();

	/**
	 * An uncommented item
	 */
	public static final TableField<String> GRANTEE = new TableFieldImpl<String>("GRANTEE", String.class, COLUMN_PRIVILEGES);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> TABLE_CATALOG = new TableFieldImpl<String>("TABLE_CATALOG", String.class, COLUMN_PRIVILEGES);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> TABLE_SCHEMA = new TableFieldImpl<String>("TABLE_SCHEMA", String.class, COLUMN_PRIVILEGES);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> TABLE_NAME = new TableFieldImpl<String>("TABLE_NAME", String.class, COLUMN_PRIVILEGES);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> COLUMN_NAME = new TableFieldImpl<String>("COLUMN_NAME", String.class, COLUMN_PRIVILEGES);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> PRIVILEGE_TYPE = new TableFieldImpl<String>("PRIVILEGE_TYPE", String.class, COLUMN_PRIVILEGES);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> IS_GRANTABLE = new TableFieldImpl<String>("IS_GRANTABLE", String.class, COLUMN_PRIVILEGES);

	/**
	 * No further instances allowed
	 */
	private ColumnPrivileges() {
		super("COLUMN_PRIVILEGES", InformationSchema.INFORMATION_SCHEMA);
	}
}
