/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.information_schema.tables;

import org.jooq.Field;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class Views extends TableImpl {

	private static final long serialVersionUID = -919807661916472915L;

	/**
	 * The singleton instance of VIEWS
	 */
	public static final Views VIEWS = new Views();

	/**
	 * An uncommented item
	 */
	public static final Field<String> TABLE_CATALOG = new TableFieldImpl<String>("TABLE_CATALOG", String.class, VIEWS);

	/**
	 * An uncommented item
	 */
	public static final Field<String> TABLE_SCHEMA = new TableFieldImpl<String>("TABLE_SCHEMA", String.class, VIEWS);

	/**
	 * An uncommented item
	 */
	public static final Field<String> TABLE_NAME = new TableFieldImpl<String>("TABLE_NAME", String.class, VIEWS);

	/**
	 * An uncommented item
	 */
	public static final Field<String> VIEW_DEFINITION = new TableFieldImpl<String>("VIEW_DEFINITION", String.class, VIEWS);

	/**
	 * An uncommented item
	 */
	public static final Field<String> CHECK_OPTION = new TableFieldImpl<String>("CHECK_OPTION", String.class, VIEWS);

	/**
	 * An uncommented item
	 */
	public static final Field<String> IS_UPDATABLE = new TableFieldImpl<String>("IS_UPDATABLE", String.class, VIEWS);

	/**
	 * An uncommented item
	 */
	public static final Field<String> DEFINER = new TableFieldImpl<String>("DEFINER", String.class, VIEWS);

	/**
	 * An uncommented item
	 */
	public static final Field<String> SECURITY_TYPE = new TableFieldImpl<String>("SECURITY_TYPE", String.class, VIEWS);

	/**
	 * An uncommented item
	 */
	public static final Field<String> CHARACTER_SET_CLIENT = new TableFieldImpl<String>("CHARACTER_SET_CLIENT", String.class, VIEWS);

	/**
	 * An uncommented item
	 */
	public static final Field<String> COLLATION_CONNECTION = new TableFieldImpl<String>("COLLATION_CONNECTION", String.class, VIEWS);

	/**
	 * No further instances allowed
	 */
	private Views() {
		super("VIEWS", "information_schema");
	}
}
