/**
 * This class is generated by jOOQ
 */
package org.jooq.util.ingres.ingres.tables.records;


import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;
import org.jooq.util.ingres.ingres.tables.Iicolumns;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class IicolumnsRecord extends TableRecordImpl<IicolumnsRecord> {

	private static final long serialVersionUID = -1732000478;

	/**
	 * An uncommented item
	 */
	public void setTableName(String value) {
		setValue(Iicolumns.TABLE_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableName() {
		return getValue(Iicolumns.TABLE_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setTableOwner(String value) {
		setValue(Iicolumns.TABLE_OWNER, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableOwner() {
		return getValue(Iicolumns.TABLE_OWNER);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnName(String value) {
		setValue(Iicolumns.COLUMN_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnName() {
		return getValue(Iicolumns.COLUMN_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnDatatype(String value) {
		setValue(Iicolumns.COLUMN_DATATYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnDatatype() {
		return getValue(Iicolumns.COLUMN_DATATYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnLength(Integer value) {
		setValue(Iicolumns.COLUMN_LENGTH, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getColumnLength() {
		return getValue(Iicolumns.COLUMN_LENGTH);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnScale(Integer value) {
		setValue(Iicolumns.COLUMN_SCALE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getColumnScale() {
		return getValue(Iicolumns.COLUMN_SCALE);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnCollid(Integer value) {
		setValue(Iicolumns.COLUMN_COLLID, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getColumnCollid() {
		return getValue(Iicolumns.COLUMN_COLLID);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnNulls(String value) {
		setValue(Iicolumns.COLUMN_NULLS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnNulls() {
		return getValue(Iicolumns.COLUMN_NULLS);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnDefaults(String value) {
		setValue(Iicolumns.COLUMN_DEFAULTS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnDefaults() {
		return getValue(Iicolumns.COLUMN_DEFAULTS);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnSequence(Integer value) {
		setValue(Iicolumns.COLUMN_SEQUENCE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getColumnSequence() {
		return getValue(Iicolumns.COLUMN_SEQUENCE);
	}

	/**
	 * An uncommented item
	 */
	public void setKeySequence(Integer value) {
		setValue(Iicolumns.KEY_SEQUENCE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getKeySequence() {
		return getValue(Iicolumns.KEY_SEQUENCE);
	}

	/**
	 * An uncommented item
	 */
	public void setSortDirection(String value) {
		setValue(Iicolumns.SORT_DIRECTION, value);
	}

	/**
	 * An uncommented item
	 */
	public String getSortDirection() {
		return getValue(Iicolumns.SORT_DIRECTION);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnIngdatatype(Integer value) {
		setValue(Iicolumns.COLUMN_INGDATATYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getColumnIngdatatype() {
		return getValue(Iicolumns.COLUMN_INGDATATYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnInternalDatatype(String value) {
		setValue(Iicolumns.COLUMN_INTERNAL_DATATYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnInternalDatatype() {
		return getValue(Iicolumns.COLUMN_INTERNAL_DATATYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnInternalLength(Integer value) {
		setValue(Iicolumns.COLUMN_INTERNAL_LENGTH, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getColumnInternalLength() {
		return getValue(Iicolumns.COLUMN_INTERNAL_LENGTH);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnInternalIngtype(Integer value) {
		setValue(Iicolumns.COLUMN_INTERNAL_INGTYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getColumnInternalIngtype() {
		return getValue(Iicolumns.COLUMN_INTERNAL_INGTYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnSystemMaintained(String value) {
		setValue(Iicolumns.COLUMN_SYSTEM_MAINTAINED, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnSystemMaintained() {
		return getValue(Iicolumns.COLUMN_SYSTEM_MAINTAINED);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnUpdateable(String value) {
		setValue(Iicolumns.COLUMN_UPDATEABLE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnUpdateable() {
		return getValue(Iicolumns.COLUMN_UPDATEABLE);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnHasDefault(String value) {
		setValue(Iicolumns.COLUMN_HAS_DEFAULT, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnHasDefault() {
		return getValue(Iicolumns.COLUMN_HAS_DEFAULT);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnDefaultVal(String value) {
		setValue(Iicolumns.COLUMN_DEFAULT_VAL, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnDefaultVal() {
		return getValue(Iicolumns.COLUMN_DEFAULT_VAL);
	}

	/**
	 * An uncommented item
	 */
	public void setSecurityAuditKey(String value) {
		setValue(Iicolumns.SECURITY_AUDIT_KEY, value);
	}

	/**
	 * An uncommented item
	 */
	public String getSecurityAuditKey() {
		return getValue(Iicolumns.SECURITY_AUDIT_KEY);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnAlwaysIdent(String value) {
		setValue(Iicolumns.COLUMN_ALWAYS_IDENT, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnAlwaysIdent() {
		return getValue(Iicolumns.COLUMN_ALWAYS_IDENT);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnBydefaultIdent(String value) {
		setValue(Iicolumns.COLUMN_BYDEFAULT_IDENT, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnBydefaultIdent() {
		return getValue(Iicolumns.COLUMN_BYDEFAULT_IDENT);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnEncrypted(String value) {
		setValue(Iicolumns.COLUMN_ENCRYPTED, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnEncrypted() {
		return getValue(Iicolumns.COLUMN_ENCRYPTED);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnEncryptWidth(Integer value) {
		setValue(Iicolumns.COLUMN_ENCRYPT_WIDTH, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getColumnEncryptWidth() {
		return getValue(Iicolumns.COLUMN_ENCRYPT_WIDTH);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnEncryptSalt(String value) {
		setValue(Iicolumns.COLUMN_ENCRYPT_SALT, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnEncryptSalt() {
		return getValue(Iicolumns.COLUMN_ENCRYPT_SALT);
	}

	/**
	 * An uncommented item
	 */
	public void setColumnEncryptCrc(String value) {
		setValue(Iicolumns.COLUMN_ENCRYPT_CRC, value);
	}

	/**
	 * An uncommented item
	 */
	public String getColumnEncryptCrc() {
		return getValue(Iicolumns.COLUMN_ENCRYPT_CRC);
	}
	/**
	 * Create a detached IicolumnsRecord
	 */
	public IicolumnsRecord() {
		super(Iicolumns.IICOLUMNS);
	}
}
