/**
 * This class is generated by jOOQ
 */
package org.jooq.util.ingres.ingres.tables.records;


import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;
import org.jooq.util.ingres.ingres.tables.Iitables;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class IitablesRecord extends TableRecordImpl<IitablesRecord> {

	private static final long serialVersionUID = -610800064;

	/**
	 * An uncommented item
	 */
	public void setTableName(String value) {
		setValue(Iitables.TABLE_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableName() {
		return getValue(Iitables.TABLE_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setTableOwner(String value) {
		setValue(Iitables.TABLE_OWNER, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableOwner() {
		return getValue(Iitables.TABLE_OWNER);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateDate(String value) {
		setValue(Iitables.CREATE_DATE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getCreateDate() {
		return getValue(Iitables.CREATE_DATE);
	}

	/**
	 * An uncommented item
	 */
	public void setAlterDate(String value) {
		setValue(Iitables.ALTER_DATE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getAlterDate() {
		return getValue(Iitables.ALTER_DATE);
	}

	/**
	 * An uncommented item
	 */
	public void setTableType(String value) {
		setValue(Iitables.TABLE_TYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableType() {
		return getValue(Iitables.TABLE_TYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setTableSubtype(String value) {
		setValue(Iitables.TABLE_SUBTYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableSubtype() {
		return getValue(Iitables.TABLE_SUBTYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setTableVersion(String value) {
		setValue(Iitables.TABLE_VERSION, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableVersion() {
		return getValue(Iitables.TABLE_VERSION);
	}

	/**
	 * An uncommented item
	 */
	public void setSystemUse(String value) {
		setValue(Iitables.SYSTEM_USE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getSystemUse() {
		return getValue(Iitables.SYSTEM_USE);
	}

	/**
	 * An uncommented item
	 */
	public void setTableStats(String value) {
		setValue(Iitables.TABLE_STATS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableStats() {
		return getValue(Iitables.TABLE_STATS);
	}

	/**
	 * An uncommented item
	 */
	public void setTableIndexes(String value) {
		setValue(Iitables.TABLE_INDEXES, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableIndexes() {
		return getValue(Iitables.TABLE_INDEXES);
	}

	/**
	 * An uncommented item
	 */
	public void setIsReadonly(String value) {
		setValue(Iitables.IS_READONLY, value);
	}

	/**
	 * An uncommented item
	 */
	public String getIsReadonly() {
		return getValue(Iitables.IS_READONLY);
	}

	/**
	 * An uncommented item
	 */
	public void setConcurrentAccess(String value) {
		setValue(Iitables.CONCURRENT_ACCESS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getConcurrentAccess() {
		return getValue(Iitables.CONCURRENT_ACCESS);
	}

	/**
	 * An uncommented item
	 */
	public void setNumRows(Integer value) {
		setValue(Iitables.NUM_ROWS, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getNumRows() {
		return getValue(Iitables.NUM_ROWS);
	}

	/**
	 * An uncommented item
	 */
	public void setStorageStructure(String value) {
		setValue(Iitables.STORAGE_STRUCTURE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getStorageStructure() {
		return getValue(Iitables.STORAGE_STRUCTURE);
	}

	/**
	 * An uncommented item
	 */
	public void setIsCompressed(String value) {
		setValue(Iitables.IS_COMPRESSED, value);
	}

	/**
	 * An uncommented item
	 */
	public String getIsCompressed() {
		return getValue(Iitables.IS_COMPRESSED);
	}

	/**
	 * An uncommented item
	 */
	public void setKeyIsCompressed(String value) {
		setValue(Iitables.KEY_IS_COMPRESSED, value);
	}

	/**
	 * An uncommented item
	 */
	public String getKeyIsCompressed() {
		return getValue(Iitables.KEY_IS_COMPRESSED);
	}

	/**
	 * An uncommented item
	 */
	public void setDuplicateRows(String value) {
		setValue(Iitables.DUPLICATE_ROWS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getDuplicateRows() {
		return getValue(Iitables.DUPLICATE_ROWS);
	}

	/**
	 * An uncommented item
	 */
	public void setUniqueRule(String value) {
		setValue(Iitables.UNIQUE_RULE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getUniqueRule() {
		return getValue(Iitables.UNIQUE_RULE);
	}

	/**
	 * An uncommented item
	 */
	public void setNumberPages(Integer value) {
		setValue(Iitables.NUMBER_PAGES, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getNumberPages() {
		return getValue(Iitables.NUMBER_PAGES);
	}

	/**
	 * An uncommented item
	 */
	public void setOverflowPages(Integer value) {
		setValue(Iitables.OVERFLOW_PAGES, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getOverflowPages() {
		return getValue(Iitables.OVERFLOW_PAGES);
	}

	/**
	 * An uncommented item
	 */
	public void setRowWidth(Integer value) {
		setValue(Iitables.ROW_WIDTH, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getRowWidth() {
		return getValue(Iitables.ROW_WIDTH);
	}

	/**
	 * An uncommented item
	 */
	public void setExpireDate(Integer value) {
		setValue(Iitables.EXPIRE_DATE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getExpireDate() {
		return getValue(Iitables.EXPIRE_DATE);
	}

	/**
	 * An uncommented item
	 */
	public void setModifyDate(String value) {
		setValue(Iitables.MODIFY_DATE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getModifyDate() {
		return getValue(Iitables.MODIFY_DATE);
	}

	/**
	 * An uncommented item
	 */
	public void setLocationName(String value) {
		setValue(Iitables.LOCATION_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getLocationName() {
		return getValue(Iitables.LOCATION_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setTableIntegrities(String value) {
		setValue(Iitables.TABLE_INTEGRITIES, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableIntegrities() {
		return getValue(Iitables.TABLE_INTEGRITIES);
	}

	/**
	 * An uncommented item
	 */
	public void setTablePermits(String value) {
		setValue(Iitables.TABLE_PERMITS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTablePermits() {
		return getValue(Iitables.TABLE_PERMITS);
	}

	/**
	 * An uncommented item
	 */
	public void setAllToAll(String value) {
		setValue(Iitables.ALL_TO_ALL, value);
	}

	/**
	 * An uncommented item
	 */
	public String getAllToAll() {
		return getValue(Iitables.ALL_TO_ALL);
	}

	/**
	 * An uncommented item
	 */
	public void setRetToAll(String value) {
		setValue(Iitables.RET_TO_ALL, value);
	}

	/**
	 * An uncommented item
	 */
	public String getRetToAll() {
		return getValue(Iitables.RET_TO_ALL);
	}

	/**
	 * An uncommented item
	 */
	public void setIsJournalled(String value) {
		setValue(Iitables.IS_JOURNALLED, value);
	}

	/**
	 * An uncommented item
	 */
	public String getIsJournalled() {
		return getValue(Iitables.IS_JOURNALLED);
	}

	/**
	 * An uncommented item
	 */
	public void setViewBase(String value) {
		setValue(Iitables.VIEW_BASE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getViewBase() {
		return getValue(Iitables.VIEW_BASE);
	}

	/**
	 * An uncommented item
	 */
	public void setMultiLocations(String value) {
		setValue(Iitables.MULTI_LOCATIONS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getMultiLocations() {
		return getValue(Iitables.MULTI_LOCATIONS);
	}

	/**
	 * An uncommented item
	 */
	public void setTableIfillpct(Integer value) {
		setValue(Iitables.TABLE_IFILLPCT, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableIfillpct() {
		return getValue(Iitables.TABLE_IFILLPCT);
	}

	/**
	 * An uncommented item
	 */
	public void setTableDfillpct(Integer value) {
		setValue(Iitables.TABLE_DFILLPCT, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableDfillpct() {
		return getValue(Iitables.TABLE_DFILLPCT);
	}

	/**
	 * An uncommented item
	 */
	public void setTableLfillpct(Integer value) {
		setValue(Iitables.TABLE_LFILLPCT, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableLfillpct() {
		return getValue(Iitables.TABLE_LFILLPCT);
	}

	/**
	 * An uncommented item
	 */
	public void setTableMinpages(Integer value) {
		setValue(Iitables.TABLE_MINPAGES, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableMinpages() {
		return getValue(Iitables.TABLE_MINPAGES);
	}

	/**
	 * An uncommented item
	 */
	public void setTableMaxpages(Integer value) {
		setValue(Iitables.TABLE_MAXPAGES, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableMaxpages() {
		return getValue(Iitables.TABLE_MAXPAGES);
	}

	/**
	 * An uncommented item
	 */
	public void setTableRelstamp1(Integer value) {
		setValue(Iitables.TABLE_RELSTAMP1, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableRelstamp1() {
		return getValue(Iitables.TABLE_RELSTAMP1);
	}

	/**
	 * An uncommented item
	 */
	public void setTableRelstamp2(Integer value) {
		setValue(Iitables.TABLE_RELSTAMP2, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableRelstamp2() {
		return getValue(Iitables.TABLE_RELSTAMP2);
	}

	/**
	 * An uncommented item
	 */
	public void setTableReltid(Integer value) {
		setValue(Iitables.TABLE_RELTID, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableReltid() {
		return getValue(Iitables.TABLE_RELTID);
	}

	/**
	 * An uncommented item
	 */
	public void setTableReltidx(Integer value) {
		setValue(Iitables.TABLE_RELTIDX, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableReltidx() {
		return getValue(Iitables.TABLE_RELTIDX);
	}

	/**
	 * An uncommented item
	 */
	public void setUniqueScope(String value) {
		setValue(Iitables.UNIQUE_SCOPE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getUniqueScope() {
		return getValue(Iitables.UNIQUE_SCOPE);
	}

	/**
	 * An uncommented item
	 */
	public void setAllocationSize(Integer value) {
		setValue(Iitables.ALLOCATION_SIZE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getAllocationSize() {
		return getValue(Iitables.ALLOCATION_SIZE);
	}

	/**
	 * An uncommented item
	 */
	public void setExtendSize(Integer value) {
		setValue(Iitables.EXTEND_SIZE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getExtendSize() {
		return getValue(Iitables.EXTEND_SIZE);
	}

	/**
	 * An uncommented item
	 */
	public void setAllocatedPages(Integer value) {
		setValue(Iitables.ALLOCATED_PAGES, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getAllocatedPages() {
		return getValue(Iitables.ALLOCATED_PAGES);
	}

	/**
	 * An uncommented item
	 */
	public void setLabelGranularity(String value) {
		setValue(Iitables.LABEL_GRANULARITY, value);
	}

	/**
	 * An uncommented item
	 */
	public String getLabelGranularity() {
		return getValue(Iitables.LABEL_GRANULARITY);
	}

	/**
	 * An uncommented item
	 */
	public void setRowSecurityAudit(String value) {
		setValue(Iitables.ROW_SECURITY_AUDIT, value);
	}

	/**
	 * An uncommented item
	 */
	public String getRowSecurityAudit() {
		return getValue(Iitables.ROW_SECURITY_AUDIT);
	}

	/**
	 * An uncommented item
	 */
	public void setSecurityLabel(String value) {
		setValue(Iitables.SECURITY_LABEL, value);
	}

	/**
	 * An uncommented item
	 */
	public String getSecurityLabel() {
		return getValue(Iitables.SECURITY_LABEL);
	}

	/**
	 * An uncommented item
	 */
	public void setTablePagesize(Integer value) {
		setValue(Iitables.TABLE_PAGESIZE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTablePagesize() {
		return getValue(Iitables.TABLE_PAGESIZE);
	}

	/**
	 * An uncommented item
	 */
	public void setTableRelversion(Integer value) {
		setValue(Iitables.TABLE_RELVERSION, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableRelversion() {
		return getValue(Iitables.TABLE_RELVERSION);
	}

	/**
	 * An uncommented item
	 */
	public void setTableReltotwid(Integer value) {
		setValue(Iitables.TABLE_RELTOTWID, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableReltotwid() {
		return getValue(Iitables.TABLE_RELTOTWID);
	}

	/**
	 * An uncommented item
	 */
	public void setTableReltcpri(Integer value) {
		setValue(Iitables.TABLE_RELTCPRI, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableReltcpri() {
		return getValue(Iitables.TABLE_RELTCPRI);
	}

	/**
	 * An uncommented item
	 */
	public void setTupsPerPage(Integer value) {
		setValue(Iitables.TUPS_PER_PAGE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTupsPerPage() {
		return getValue(Iitables.TUPS_PER_PAGE);
	}

	/**
	 * An uncommented item
	 */
	public void setKeysPerPage(Integer value) {
		setValue(Iitables.KEYS_PER_PAGE, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getKeysPerPage() {
		return getValue(Iitables.KEYS_PER_PAGE);
	}

	/**
	 * An uncommented item
	 */
	public void setKeysPerLeaf(Integer value) {
		setValue(Iitables.KEYS_PER_LEAF, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getKeysPerLeaf() {
		return getValue(Iitables.KEYS_PER_LEAF);
	}

	/**
	 * An uncommented item
	 */
	public void setPhysPartitions(Integer value) {
		setValue(Iitables.PHYS_PARTITIONS, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getPhysPartitions() {
		return getValue(Iitables.PHYS_PARTITIONS);
	}

	/**
	 * An uncommented item
	 */
	public void setPartitionDimensions(Integer value) {
		setValue(Iitables.PARTITION_DIMENSIONS, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getPartitionDimensions() {
		return getValue(Iitables.PARTITION_DIMENSIONS);
	}

	/**
	 * An uncommented item
	 */
	public void setTableReldatawid(Integer value) {
		setValue(Iitables.TABLE_RELDATAWID, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableReldatawid() {
		return getValue(Iitables.TABLE_RELDATAWID);
	}

	/**
	 * An uncommented item
	 */
	public void setTableReltotdatawid(Integer value) {
		setValue(Iitables.TABLE_RELTOTDATAWID, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTableReltotdatawid() {
		return getValue(Iitables.TABLE_RELTOTDATAWID);
	}

	/**
	 * An uncommented item
	 */
	public void setEncryptedColumns(String value) {
		setValue(Iitables.ENCRYPTED_COLUMNS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getEncryptedColumns() {
		return getValue(Iitables.ENCRYPTED_COLUMNS);
	}

	/**
	 * An uncommented item
	 */
	public void setEncryptionVersion(Integer value) {
		setValue(Iitables.ENCRYPTION_VERSION, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getEncryptionVersion() {
		return getValue(Iitables.ENCRYPTION_VERSION);
	}

	/**
	 * An uncommented item
	 */
	public void setEncryptionType(String value) {
		setValue(Iitables.ENCRYPTION_TYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getEncryptionType() {
		return getValue(Iitables.ENCRYPTION_TYPE);
	}
	/**
	 * Create a detached IitablesRecord
	 */
	public IitablesRecord() {
		super(Iitables.IITABLES);
	}
}
