/**
 * This class is generated by jOOQ
 */
package org.jooq.test.oracle.generatedclasses;


import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;

import javax.annotation.Generated;

import org.jooq.test.oracle.generatedclasses.procedures.F378;
import org.jooq.test.oracle.generatedclasses.procedures.P377;
import org.jooq.test.oracle.generatedclasses.procedures.P391;
import org.jooq.test.oracle.generatedclasses.procedures.PArrays1;
import org.jooq.test.oracle.generatedclasses.procedures.PArrays2;
import org.jooq.test.oracle.generatedclasses.procedures.PArrays3;
import org.jooq.test.oracle.generatedclasses.procedures.PAuthorExists;
import org.jooq.test.oracle.generatedclasses.procedures.PCreateAuthor;
import org.jooq.test.oracle.generatedclasses.procedures.PCreateAuthorByName;
import org.jooq.test.oracle.generatedclasses.procedures.PEnhanceAddress1;
import org.jooq.test.oracle.generatedclasses.procedures.PEnhanceAddress2;
import org.jooq.test.oracle.generatedclasses.procedures.PEnhanceAddress3;
import org.jooq.test.oracle.generatedclasses.procedures.PUnused;
import org.jooq.test.oracle.generatedclasses.udt.records.UAddressTypeRecord;
import org.jooq.test.oracle.generatedclasses.udt.records.UNumberArrayRecord;
import org.jooq.test.oracle.generatedclasses.udt.records.UNumberLongArrayRecord;
import org.jooq.test.oracle.generatedclasses.udt.records.UStringArrayRecord;


/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all stored procedures in TEST
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public final class Procedures {

	/**
	 * Invoke F378
	 *
	 * @param returnValue OUT parameter
	 * @param i IN parameter
	 * @param io IN OUT parameter
	 * @param o OUT parameter
	 */
	public static F378 f378(Connection connection, Number i, Number io) throws SQLException {
		F378 p = new F378();
		p.setI(i);
		p.setIo(io);

		p.execute(connection);
		return p;
	}

	/**
	 * Invoke P_ARRAYS1
	 *
	 * @param inArray IN parameter
	 * @param outArray OUT parameter
	 */
	public static UNumberArrayRecord pArrays1(Connection connection, UNumberArrayRecord inArray) throws SQLException {
		PArrays1 p = new PArrays1();
		p.setInArray(inArray);

		p.execute(connection);
		return p.getOutArray();
	}

	/**
	 * Invoke P_ARRAYS2
	 *
	 * @param inArray IN parameter
	 * @param outArray OUT parameter
	 */
	public static UNumberLongArrayRecord pArrays2(Connection connection, UNumberLongArrayRecord inArray) throws SQLException {
		PArrays2 p = new PArrays2();
		p.setInArray(inArray);

		p.execute(connection);
		return p.getOutArray();
	}

	/**
	 * Invoke P_ARRAYS3
	 *
	 * @param inArray IN parameter
	 * @param outArray OUT parameter
	 */
	public static UStringArrayRecord pArrays3(Connection connection, UStringArrayRecord inArray) throws SQLException {
		PArrays3 p = new PArrays3();
		p.setInArray(inArray);

		p.execute(connection);
		return p.getOutArray();
	}

	/**
	 * Invoke P_AUTHOR_EXISTS
	 *
	 * @param authorName IN parameter
	 * @param result OUT parameter
	 */
	public static BigDecimal pAuthorExists(Connection connection, String authorName) throws SQLException {
		PAuthorExists p = new PAuthorExists();
		p.setAuthorName(authorName);

		p.execute(connection);
		return p.getResult();
	}

	/**
	 * Invoke P_CREATE_AUTHOR
	 *
	 */
	public static void pCreateAuthor(Connection connection) throws SQLException {
		PCreateAuthor p = new PCreateAuthor();

		p.execute(connection);
	}

	/**
	 * Invoke P_CREATE_AUTHOR_BY_NAME
	 *
	 * @param firstName IN parameter
	 * @param lastName IN parameter
	 */
	public static void pCreateAuthorByName(Connection connection, String firstName, String lastName) throws SQLException {
		PCreateAuthorByName p = new PCreateAuthorByName();
		p.setFirstName(firstName);
		p.setLastName(lastName);

		p.execute(connection);
	}

	/**
	 * Invoke P_ENHANCE_ADDRESS1
	 *
	 * @param address IN parameter
	 * @param no OUT parameter
	 */
	public static String pEnhanceAddress1(Connection connection, UAddressTypeRecord address) throws SQLException {
		PEnhanceAddress1 p = new PEnhanceAddress1();
		p.setAddress(address);

		p.execute(connection);
		return p.getNo();
	}

	/**
	 * Invoke P_ENHANCE_ADDRESS2
	 *
	 * @param address OUT parameter
	 */
	public static UAddressTypeRecord pEnhanceAddress2(Connection connection) throws SQLException {
		PEnhanceAddress2 p = new PEnhanceAddress2();

		p.execute(connection);
		return p.getAddress();
	}

	/**
	 * Invoke P_ENHANCE_ADDRESS3
	 *
	 * @param address IN OUT parameter
	 */
	public static UAddressTypeRecord pEnhanceAddress3(Connection connection, UAddressTypeRecord address) throws SQLException {
		PEnhanceAddress3 p = new PEnhanceAddress3();
		p.setAddress(address);

		p.execute(connection);
		return p.getAddress();
	}

	/**
	 * Invoke P_UNUSED
	 *
	 * @param in1 IN parameter
	 * @param out1 OUT parameter
	 * @param out2 IN OUT parameter
	 */
	public static PUnused pUnused(Connection connection, String in1, Number out2) throws SQLException {
		PUnused p = new PUnused();
		p.setIn1(in1);
		p.setOut2(out2);

		p.execute(connection);
		return p;
	}

	/**
	 * Invoke P377
	 *
	 */
	public static void p377(Connection connection) throws SQLException {
		P377 p = new P377();

		p.execute(connection);
	}

	/**
	 * Invoke P391
	 *
	 * @param i1 IN parameter
	 * @param io1 IN OUT parameter
	 * @param o1 OUT parameter
	 * @param o2 OUT parameter
	 * @param io2 IN OUT parameter
	 * @param i2 IN parameter
	 */
	public static P391 p391(Connection connection, Number i1, Number io1, Number io2, Number i2) throws SQLException {
		P391 p = new P391();
		p.setI1(i1);
		p.setIo1(io1);
		p.setIo2(io2);
		p.setI2(i2);

		p.execute(connection);
		return p;
	}

	/**
	 * No instances
	 */
	private Procedures() {}
}
