/**
 * This class is generated by jOOQ
 */
package org.jooq.util.db2.syscat.tables;


import javax.annotation.Generated;

import org.jooq.SQLDialect;
import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.db2.syscat.Syscat;
import org.jooq.util.db2.syscat.tables.records.FuncparmsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class Funcparms extends TableImpl<FuncparmsRecord> {

	private static final long serialVersionUID = -123230294;

	/**
	 * The singleton instance of FUNCPARMS
	 */
	public static final Funcparms FUNCPARMS = new Funcparms();

	/**
	 * The class holding records for this type
	 */
	private static final Class<FuncparmsRecord> __RECORD_TYPE = FuncparmsRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FuncparmsRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, String> FUNCSCHEMA = new TableFieldImpl<FuncparmsRecord, String>(SQLDialect.DB2, "FUNCSCHEMA", String.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, String> FUNCNAME = new TableFieldImpl<FuncparmsRecord, String>(SQLDialect.DB2, "FUNCNAME", String.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, String> SPECIFICNAME = new TableFieldImpl<FuncparmsRecord, String>(SQLDialect.DB2, "SPECIFICNAME", String.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, String> ROWTYPE = new TableFieldImpl<FuncparmsRecord, String>(SQLDialect.DB2, "ROWTYPE", String.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, Short> ORDINAL = new TableFieldImpl<FuncparmsRecord, Short>(SQLDialect.DB2, "ORDINAL", Short.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, String> PARMNAME = new TableFieldImpl<FuncparmsRecord, String>(SQLDialect.DB2, "PARMNAME", String.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, String> TYPESCHEMA = new TableFieldImpl<FuncparmsRecord, String>(SQLDialect.DB2, "TYPESCHEMA", String.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, String> TYPENAME = new TableFieldImpl<FuncparmsRecord, String>(SQLDialect.DB2, "TYPENAME", String.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, Integer> LENGTH = new TableFieldImpl<FuncparmsRecord, Integer>(SQLDialect.DB2, "LENGTH", Integer.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, Short> SCALE = new TableFieldImpl<FuncparmsRecord, Short>(SQLDialect.DB2, "SCALE", Short.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, Short> CODEPAGE = new TableFieldImpl<FuncparmsRecord, Short>(SQLDialect.DB2, "CODEPAGE", Short.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, Integer> CAST_FUNCID = new TableFieldImpl<FuncparmsRecord, Integer>(SQLDialect.DB2, "CAST_FUNCID", Integer.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, String> AS_LOCATOR = new TableFieldImpl<FuncparmsRecord, String>(SQLDialect.DB2, "AS_LOCATOR", String.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, String> TARGET_TYPESCHEMA = new TableFieldImpl<FuncparmsRecord, String>(SQLDialect.DB2, "TARGET_TYPESCHEMA", String.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, String> TARGET_TYPENAME = new TableFieldImpl<FuncparmsRecord, String>(SQLDialect.DB2, "TARGET_TYPENAME", String.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, String> SCOPE_TABSCHEMA = new TableFieldImpl<FuncparmsRecord, String>(SQLDialect.DB2, "SCOPE_TABSCHEMA", String.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, String> SCOPE_TABNAME = new TableFieldImpl<FuncparmsRecord, String>(SQLDialect.DB2, "SCOPE_TABNAME", String.class, FUNCPARMS);

	/**
	 * An uncommented item
	 */
	public static final TableField<FuncparmsRecord, String> TRANSFORM_GRPNAME = new TableFieldImpl<FuncparmsRecord, String>(SQLDialect.DB2, "TRANSFORM_GRPNAME", String.class, FUNCPARMS);

	/**
	 * No further instances allowed
	 */
	private Funcparms() {
		super(SQLDialect.DB2, "FUNCPARMS", Syscat.SYSCAT);
	}

}
