/**
 * This class is generated by jOOQ
 */
package org.jooq.util.h2.information_schema.tables;


import javax.annotation.Generated;

import org.jooq.TableField;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.h2.information_schema.InformationSchema;
import org.jooq.util.h2.information_schema.tables.records.TablesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class Tables extends TableImpl<TablesRecord> {

	private static final long serialVersionUID = 319075435;

	/**
	 * The singleton instance of TABLES
	 */
	public static final Tables TABLES = new Tables();

	/**
	 * The class holding records for this type
	 */
	private static final Class<TablesRecord> __RECORD_TYPE = TablesRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TablesRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<TablesRecord, String> TABLE_CATALOG = new TableFieldImpl<TablesRecord, String>("TABLE_CATALOG", SQLDataType.VARCHAR, TABLES);

	/**
	 * An uncommented item
	 */
	public static final TableField<TablesRecord, String> TABLE_SCHEMA = new TableFieldImpl<TablesRecord, String>("TABLE_SCHEMA", SQLDataType.VARCHAR, TABLES);

	/**
	 * An uncommented item
	 */
	public static final TableField<TablesRecord, String> TABLE_NAME = new TableFieldImpl<TablesRecord, String>("TABLE_NAME", SQLDataType.VARCHAR, TABLES);

	/**
	 * An uncommented item
	 */
	public static final TableField<TablesRecord, String> TABLE_TYPE = new TableFieldImpl<TablesRecord, String>("TABLE_TYPE", SQLDataType.VARCHAR, TABLES);

	/**
	 * An uncommented item
	 */
	public static final TableField<TablesRecord, String> STORAGE_TYPE = new TableFieldImpl<TablesRecord, String>("STORAGE_TYPE", SQLDataType.VARCHAR, TABLES);

	/**
	 * An uncommented item
	 */
	public static final TableField<TablesRecord, String> SQL = new TableFieldImpl<TablesRecord, String>("SQL", SQLDataType.VARCHAR, TABLES);

	/**
	 * An uncommented item
	 */
	public static final TableField<TablesRecord, String> REMARKS = new TableFieldImpl<TablesRecord, String>("REMARKS", SQLDataType.VARCHAR, TABLES);

	/**
	 * An uncommented item
	 */
	public static final TableField<TablesRecord, Long> LAST_MODIFICATION = new TableFieldImpl<TablesRecord, Long>("LAST_MODIFICATION", SQLDataType.BIGINT, TABLES);

	/**
	 * An uncommented item
	 */
	public static final TableField<TablesRecord, Integer> ID = new TableFieldImpl<TablesRecord, Integer>("ID", SQLDataType.INTEGER, TABLES);

	/**
	 * An uncommented item
	 */
	public static final TableField<TablesRecord, String> TYPE_NAME = new TableFieldImpl<TablesRecord, String>("TYPE_NAME", SQLDataType.VARCHAR, TABLES);

	/**
	 * An uncommented item
	 */
	public static final TableField<TablesRecord, String> TABLE_CLASS = new TableFieldImpl<TablesRecord, String>("TABLE_CLASS", SQLDataType.VARCHAR, TABLES);

	/**
	 * No further instances allowed
	 */
	private Tables() {
		super("TABLES", InformationSchema.INFORMATION_SCHEMA);
	}
}
