/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.information_schema;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.util.mysql.information_schema.tables.Columns;
import org.jooq.util.mysql.information_schema.tables.KeyColumnUsage;
import org.jooq.util.mysql.information_schema.tables.ReferentialConstraints;
import org.jooq.util.mysql.information_schema.tables.TableConstraints;
import org.jooq.util.mysql.information_schema.tables.Tables;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class InformationSchema extends SchemaImpl {

	private static final long serialVersionUID = 413578357;

	/**
	 * The singleton instance of information_schema
	 */
	public static final InformationSchema INFORMATION_SCHEMA = new InformationSchema();

	/**
	 * No further instances allowed
	 */
	private InformationSchema() {
		super("information_schema");
	}

	@Override
	public final List<Table<?>> getTables() {
		return Arrays.<Table<?>>asList(
			Columns.COLUMNS,
			KeyColumnUsage.KEY_COLUMN_USAGE,
			ReferentialConstraints.REFERENTIAL_CONSTRAINTS,
			Tables.TABLES,
			TableConstraints.TABLE_CONSTRAINTS);
	}
}
