/**
 * This class is generated by jOOQ
 */
package org.jooq.util.postgres.pg_catalog;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.util.postgres.pg_catalog.tables.PgAttribute;
import org.jooq.util.postgres.pg_catalog.tables.PgClass;
import org.jooq.util.postgres.pg_catalog.tables.PgEnum;
import org.jooq.util.postgres.pg_catalog.tables.PgProc;
import org.jooq.util.postgres.pg_catalog.tables.PgType;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class PgCatalog extends SchemaImpl {

	private static final long serialVersionUID = -299204300;

	/**
	 * The singleton instance of pg_catalog
	 */
	public static final PgCatalog PG_CATALOG = new PgCatalog();

	/**
	 * No further instances allowed
	 */
	private PgCatalog() {
		super("pg_catalog");
	}

	@Override
	public final List<Table<?>> getTables() {
		return Arrays.<Table<?>>asList(
			PgAttribute.PG_ATTRIBUTE,
			PgClass.PG_CLASS,
			PgEnum.PG_ENUM,
			PgProc.PG_PROC,
			PgType.PG_TYPE);
	}
}
