/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.information_schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.TableRecordImpl;
import org.jooq.util.mysql.information_schema.tables.Tables;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class TablesRecord extends TableRecordImpl<TablesRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * An uncommented item
	 */
	public void setTableCatalog(String value) {
		setValue(Tables.TABLE_CATALOG, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableCatalog() {
		return getValue(Tables.TABLE_CATALOG);
	}

	/**
	 * An uncommented item
	 */
	public void setTableSchema(String value) {
		setValue(Tables.TABLE_SCHEMA, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableSchema() {
		return getValue(Tables.TABLE_SCHEMA);
	}

	/**
	 * An uncommented item
	 */
	public void setTableName(String value) {
		setValue(Tables.TABLE_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableName() {
		return getValue(Tables.TABLE_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setTableType(String value) {
		setValue(Tables.TABLE_TYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableType() {
		return getValue(Tables.TABLE_TYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setEngine(String value) {
		setValue(Tables.ENGINE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getEngine() {
		return getValue(Tables.ENGINE);
	}

	/**
	 * An uncommented item
	 */
	public void setVersion(Long value) {
		setValue(Tables.VERSION, value);
	}

	/**
	 * An uncommented item
	 */
	public Long getVersion() {
		return getValue(Tables.VERSION);
	}

	/**
	 * An uncommented item
	 */
	public void setRowFormat(String value) {
		setValue(Tables.ROW_FORMAT, value);
	}

	/**
	 * An uncommented item
	 */
	public String getRowFormat() {
		return getValue(Tables.ROW_FORMAT);
	}

	/**
	 * An uncommented item
	 */
	public void setTableRows(Long value) {
		setValue(Tables.TABLE_ROWS, value);
	}

	/**
	 * An uncommented item
	 */
	public Long getTableRows() {
		return getValue(Tables.TABLE_ROWS);
	}

	/**
	 * An uncommented item
	 */
	public void setAvgRowLength(Long value) {
		setValue(Tables.AVG_ROW_LENGTH, value);
	}

	/**
	 * An uncommented item
	 */
	public Long getAvgRowLength() {
		return getValue(Tables.AVG_ROW_LENGTH);
	}

	/**
	 * An uncommented item
	 */
	public void setDataLength(Long value) {
		setValue(Tables.DATA_LENGTH, value);
	}

	/**
	 * An uncommented item
	 */
	public Long getDataLength() {
		return getValue(Tables.DATA_LENGTH);
	}

	/**
	 * An uncommented item
	 */
	public void setMaxDataLength(Long value) {
		setValue(Tables.MAX_DATA_LENGTH, value);
	}

	/**
	 * An uncommented item
	 */
	public Long getMaxDataLength() {
		return getValue(Tables.MAX_DATA_LENGTH);
	}

	/**
	 * An uncommented item
	 */
	public void setIndexLength(Long value) {
		setValue(Tables.INDEX_LENGTH, value);
	}

	/**
	 * An uncommented item
	 */
	public Long getIndexLength() {
		return getValue(Tables.INDEX_LENGTH);
	}

	/**
	 * An uncommented item
	 */
	public void setDataFree(Long value) {
		setValue(Tables.DATA_FREE, value);
	}

	/**
	 * An uncommented item
	 */
	public Long getDataFree() {
		return getValue(Tables.DATA_FREE);
	}

	/**
	 * An uncommented item
	 */
	public void setAutoIncrement(Long value) {
		setValue(Tables.AUTO_INCREMENT, value);
	}

	/**
	 * An uncommented item
	 */
	public Long getAutoIncrement() {
		return getValue(Tables.AUTO_INCREMENT);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(Timestamp value) {
		setValue(Tables.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public Timestamp getCreateTime() {
		return getValue(Tables.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setUpdateTime(Timestamp value) {
		setValue(Tables.UPDATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public Timestamp getUpdateTime() {
		return getValue(Tables.UPDATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setCheckTime(Timestamp value) {
		setValue(Tables.CHECK_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public Timestamp getCheckTime() {
		return getValue(Tables.CHECK_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setTableCollation(String value) {
		setValue(Tables.TABLE_COLLATION, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableCollation() {
		return getValue(Tables.TABLE_COLLATION);
	}

	/**
	 * An uncommented item
	 */
	public void setChecksum(Long value) {
		setValue(Tables.CHECKSUM, value);
	}

	/**
	 * An uncommented item
	 */
	public Long getChecksum() {
		return getValue(Tables.CHECKSUM);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateOptions(String value) {
		setValue(Tables.CREATE_OPTIONS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getCreateOptions() {
		return getValue(Tables.CREATE_OPTIONS);
	}

	/**
	 * An uncommented item
	 */
	public void setTableComment(String value) {
		setValue(Tables.TABLE_COMMENT, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableComment() {
		return getValue(Tables.TABLE_COMMENT);
	}

	public TablesRecord(Configuration configuration) {
		super(configuration, Tables.TABLES);
	}
}
