/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.information_schema.tables.records;

import java.sql.Timestamp;
import org.jooq.Result;
import org.jooq.impl.RecordImpl;
import org.jooq.util.mysql.information_schema.tables.Triggers;


/**
 * This class is generated by jOOQ.
 */
public class TriggersRecord extends RecordImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * An uncommented item
	 */
	public void setTriggerCatalog(String value) {
		setValue(Triggers.TRIGGER_CATALOG, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTriggerCatalog() {
		return getValue(Triggers.TRIGGER_CATALOG);
	}

	/**
	 * An uncommented item
	 */
	public void setTriggerSchema(String value) {
		setValue(Triggers.TRIGGER_SCHEMA, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTriggerSchema() {
		return getValue(Triggers.TRIGGER_SCHEMA);
	}

	/**
	 * An uncommented item
	 */
	public void setTriggerName(String value) {
		setValue(Triggers.TRIGGER_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTriggerName() {
		return getValue(Triggers.TRIGGER_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setEventManipulation(String value) {
		setValue(Triggers.EVENT_MANIPULATION, value);
	}

	/**
	 * An uncommented item
	 */
	public String getEventManipulation() {
		return getValue(Triggers.EVENT_MANIPULATION);
	}

	/**
	 * An uncommented item
	 */
	public void setEventObjectCatalog(String value) {
		setValue(Triggers.EVENT_OBJECT_CATALOG, value);
	}

	/**
	 * An uncommented item
	 */
	public String getEventObjectCatalog() {
		return getValue(Triggers.EVENT_OBJECT_CATALOG);
	}

	/**
	 * An uncommented item
	 */
	public void setEventObjectSchema(String value) {
		setValue(Triggers.EVENT_OBJECT_SCHEMA, value);
	}

	/**
	 * An uncommented item
	 */
	public String getEventObjectSchema() {
		return getValue(Triggers.EVENT_OBJECT_SCHEMA);
	}

	/**
	 * An uncommented item
	 */
	public void setEventObjectTable(String value) {
		setValue(Triggers.EVENT_OBJECT_TABLE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getEventObjectTable() {
		return getValue(Triggers.EVENT_OBJECT_TABLE);
	}

	/**
	 * An uncommented item
	 */
	public void setActionOrder(Integer value) {
		setValue(Triggers.ACTION_ORDER, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getActionOrder() {
		return getValue(Triggers.ACTION_ORDER);
	}

	/**
	 * An uncommented item
	 */
	public void setActionCondition(String value) {
		setValue(Triggers.ACTION_CONDITION, value);
	}

	/**
	 * An uncommented item
	 */
	public String getActionCondition() {
		return getValue(Triggers.ACTION_CONDITION);
	}

	/**
	 * An uncommented item
	 */
	public void setActionStatement(String value) {
		setValue(Triggers.ACTION_STATEMENT, value);
	}

	/**
	 * An uncommented item
	 */
	public String getActionStatement() {
		return getValue(Triggers.ACTION_STATEMENT);
	}

	/**
	 * An uncommented item
	 */
	public void setActionOrientation(String value) {
		setValue(Triggers.ACTION_ORIENTATION, value);
	}

	/**
	 * An uncommented item
	 */
	public String getActionOrientation() {
		return getValue(Triggers.ACTION_ORIENTATION);
	}

	/**
	 * An uncommented item
	 */
	public void setActionTiming(String value) {
		setValue(Triggers.ACTION_TIMING, value);
	}

	/**
	 * An uncommented item
	 */
	public String getActionTiming() {
		return getValue(Triggers.ACTION_TIMING);
	}

	/**
	 * An uncommented item
	 */
	public void setActionReferenceOldTable(String value) {
		setValue(Triggers.ACTION_REFERENCE_OLD_TABLE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getActionReferenceOldTable() {
		return getValue(Triggers.ACTION_REFERENCE_OLD_TABLE);
	}

	/**
	 * An uncommented item
	 */
	public void setActionReferenceNewTable(String value) {
		setValue(Triggers.ACTION_REFERENCE_NEW_TABLE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getActionReferenceNewTable() {
		return getValue(Triggers.ACTION_REFERENCE_NEW_TABLE);
	}

	/**
	 * An uncommented item
	 */
	public void setActionReferenceOldRow(String value) {
		setValue(Triggers.ACTION_REFERENCE_OLD_ROW, value);
	}

	/**
	 * An uncommented item
	 */
	public String getActionReferenceOldRow() {
		return getValue(Triggers.ACTION_REFERENCE_OLD_ROW);
	}

	/**
	 * An uncommented item
	 */
	public void setActionReferenceNewRow(String value) {
		setValue(Triggers.ACTION_REFERENCE_NEW_ROW, value);
	}

	/**
	 * An uncommented item
	 */
	public String getActionReferenceNewRow() {
		return getValue(Triggers.ACTION_REFERENCE_NEW_ROW);
	}

	/**
	 * An uncommented item
	 */
	public void setCreated(Timestamp value) {
		setValue(Triggers.CREATED, value);
	}

	/**
	 * An uncommented item
	 */
	public Timestamp getCreated() {
		return getValue(Triggers.CREATED);
	}

	/**
	 * An uncommented item
	 */
	public void setSqlMode(String value) {
		setValue(Triggers.SQL_MODE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getSqlMode() {
		return getValue(Triggers.SQL_MODE);
	}

	/**
	 * An uncommented item
	 */
	public void setDefiner(String value) {
		setValue(Triggers.DEFINER, value);
	}

	/**
	 * An uncommented item
	 */
	public String getDefiner() {
		return getValue(Triggers.DEFINER);
	}

	/**
	 * An uncommented item
	 */
	public void setCharacterSetClient(String value) {
		setValue(Triggers.CHARACTER_SET_CLIENT, value);
	}

	/**
	 * An uncommented item
	 */
	public String getCharacterSetClient() {
		return getValue(Triggers.CHARACTER_SET_CLIENT);
	}

	/**
	 * An uncommented item
	 */
	public void setCollationConnection(String value) {
		setValue(Triggers.COLLATION_CONNECTION, value);
	}

	/**
	 * An uncommented item
	 */
	public String getCollationConnection() {
		return getValue(Triggers.COLLATION_CONNECTION);
	}

	/**
	 * An uncommented item
	 */
	public void setDatabaseCollation(String value) {
		setValue(Triggers.DATABASE_COLLATION, value);
	}

	/**
	 * An uncommented item
	 */
	public String getDatabaseCollation() {
		return getValue(Triggers.DATABASE_COLLATION);
	}

	public TriggersRecord(Result result) {
		super(result);
	}
}
