/**
 * This class is generated by jOOQ
 */
package org.jooq.util.ingres.ingres.tables;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.SQLDialect;
import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.ingres.IngresDataType;
import org.jooq.util.ingres.ingres.$ingres;
import org.jooq.util.ingres.ingres.tables.records.IisequencesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class Iisequences extends TableImpl<IisequencesRecord> {

	private static final long serialVersionUID = 1801695965;

	/**
	 * The singleton instance of iisequences
	 */
	public static final Iisequences IISEQUENCES = new Iisequences();

	/**
	 * The class holding records for this type
	 */
	private static final Class<IisequencesRecord> __RECORD_TYPE = IisequencesRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<IisequencesRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, String> SEQ_NAME = new TableFieldImpl<IisequencesRecord, String>(SQLDialect.INGRES, "seq_name", IngresDataType.CHAR, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, String> SEQ_OWNER = new TableFieldImpl<IisequencesRecord, String>(SQLDialect.INGRES, "seq_owner", IngresDataType.CHAR, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, Date> CREATE_DATE = new TableFieldImpl<IisequencesRecord, Date>(SQLDialect.INGRES, "create_date", IngresDataType.INGRESDATE, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, Date> MODIFY_DATE = new TableFieldImpl<IisequencesRecord, Date>(SQLDialect.INGRES, "modify_date", IngresDataType.INGRESDATE, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, String> DATA_TYPE = new TableFieldImpl<IisequencesRecord, String>(SQLDialect.INGRES, "data_type", IngresDataType.VARCHAR, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, Integer> SEQ_LENGTH = new TableFieldImpl<IisequencesRecord, Integer>(SQLDialect.INGRES, "seq_length", IngresDataType.INTEGER, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, Integer> SEQ_PRECISION = new TableFieldImpl<IisequencesRecord, Integer>(SQLDialect.INGRES, "seq_precision", IngresDataType.INTEGER, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, BigDecimal> START_VALUE = new TableFieldImpl<IisequencesRecord, BigDecimal>(SQLDialect.INGRES, "start_value", IngresDataType.DECIMAL, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, BigDecimal> INCREMENT_VALUE = new TableFieldImpl<IisequencesRecord, BigDecimal>(SQLDialect.INGRES, "increment_value", IngresDataType.DECIMAL, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, BigDecimal> NEXT_VALUE = new TableFieldImpl<IisequencesRecord, BigDecimal>(SQLDialect.INGRES, "next_value", IngresDataType.DECIMAL, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, BigDecimal> MIN_VALUE = new TableFieldImpl<IisequencesRecord, BigDecimal>(SQLDialect.INGRES, "min_value", IngresDataType.DECIMAL, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, BigDecimal> MAX_VALUE = new TableFieldImpl<IisequencesRecord, BigDecimal>(SQLDialect.INGRES, "max_value", IngresDataType.DECIMAL, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, Integer> CACHE_SIZE = new TableFieldImpl<IisequencesRecord, Integer>(SQLDialect.INGRES, "cache_size", IngresDataType.INTEGER, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, String> START_FLAG = new TableFieldImpl<IisequencesRecord, String>(SQLDialect.INGRES, "start_flag", IngresDataType.CHAR, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, String> INCR_FLAG = new TableFieldImpl<IisequencesRecord, String>(SQLDialect.INGRES, "incr_flag", IngresDataType.CHAR, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, String> MIN_FLAG = new TableFieldImpl<IisequencesRecord, String>(SQLDialect.INGRES, "min_flag", IngresDataType.CHAR, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, String> MAX_FLAG = new TableFieldImpl<IisequencesRecord, String>(SQLDialect.INGRES, "max_flag", IngresDataType.CHAR, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, String> RESTART_FLAG = new TableFieldImpl<IisequencesRecord, String>(SQLDialect.INGRES, "restart_flag", IngresDataType.CHAR, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, String> CACHE_FLAG = new TableFieldImpl<IisequencesRecord, String>(SQLDialect.INGRES, "cache_flag", IngresDataType.CHAR, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, String> CYCLE_FLAG = new TableFieldImpl<IisequencesRecord, String>(SQLDialect.INGRES, "cycle_flag", IngresDataType.CHAR, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, String> ORDER_FLAG = new TableFieldImpl<IisequencesRecord, String>(SQLDialect.INGRES, "order_flag", IngresDataType.CHAR, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, String> SEQL_FLAG = new TableFieldImpl<IisequencesRecord, String>(SQLDialect.INGRES, "seql_flag", IngresDataType.CHAR, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, String> UNORDERED_FLAG = new TableFieldImpl<IisequencesRecord, String>(SQLDialect.INGRES, "unordered_flag", IngresDataType.CHAR, IISEQUENCES);

	/**
	 * An uncommented item
	 */
	public static final TableField<IisequencesRecord, String> IDENT_FLAG = new TableFieldImpl<IisequencesRecord, String>(SQLDialect.INGRES, "ident_flag", IngresDataType.CHAR, IISEQUENCES);

	/**
	 * No further instances allowed
	 */
	private Iisequences() {
		super(SQLDialect.INGRES, "iisequences", $ingres.$INGRES);
	}
}
