/**
 * This class is generated by jOOQ
 */
package org.jooq.util.sybase.sys.tables;


import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.SQLDialect;
import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.sybase.SybaseDataType;
import org.jooq.util.sybase.sys.Sys;
import org.jooq.util.sybase.sys.tables.records.SysidxRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class Sysidx extends TableImpl<SysidxRecord> {

	private static final long serialVersionUID = 1943910554;

	/**
	 * The singleton instance of SYSIDX
	 */
	public static final Sysidx SYSIDX = new Sysidx();

	/**
	 * The class holding records for this type
	 */
	private static final Class<SysidxRecord> __RECORD_TYPE = SysidxRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SysidxRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxRecord, Integer> TABLE_ID = new TableFieldImpl<SysidxRecord, Integer>(SQLDialect.SYBASE, "table_id", SybaseDataType.UNSIGNEDINT, SYSIDX);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxRecord, Integer> INDEX_ID = new TableFieldImpl<SysidxRecord, Integer>(SQLDialect.SYBASE, "index_id", SybaseDataType.UNSIGNEDINT, SYSIDX);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxRecord, BigInteger> OBJECT_ID = new TableFieldImpl<SysidxRecord, BigInteger>(SQLDialect.SYBASE, "object_id", SybaseDataType.UNSIGNEDBIGINT, SYSIDX);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxRecord, Integer> PHYS_INDEX_ID = new TableFieldImpl<SysidxRecord, Integer>(SQLDialect.SYBASE, "phys_index_id", SybaseDataType.UNSIGNEDINT, SYSIDX);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxRecord, Integer> DBSPACE_ID = new TableFieldImpl<SysidxRecord, Integer>(SQLDialect.SYBASE, "dbspace_id", SybaseDataType.SMALLINT, SYSIDX);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxRecord, Integer> INDEX_CATEGORY = new TableFieldImpl<SysidxRecord, Integer>(SQLDialect.SYBASE, "index_category", SybaseDataType.TINYINT, SYSIDX);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxRecord, Integer> UNIQUE = new TableFieldImpl<SysidxRecord, Integer>(SQLDialect.SYBASE, "unique", SybaseDataType.TINYINT, SYSIDX);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxRecord, String> INDEX_NAME = new TableFieldImpl<SysidxRecord, String>(SQLDialect.SYBASE, "index_name", SybaseDataType.CHAR, SYSIDX);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxRecord, String> NOT_ENFORCED = new TableFieldImpl<SysidxRecord, String>(SQLDialect.SYBASE, "not_enforced", SybaseDataType.CHAR, SYSIDX);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxRecord, Integer> FILE_ID = new TableFieldImpl<SysidxRecord, Integer>(SQLDialect.SYBASE, "file_id", SybaseDataType.SMALLINT, SYSIDX);

	/**
	 * No further instances allowed
	 */
	private Sysidx() {
		super(SQLDialect.SYBASE, "SYSIDX", Sys.SYS);
	}
}
