/**
 * This class is generated by jOOQ
 */
package org.jooq.util.sybase.sys.tables;


import javax.annotation.Generated;

import org.jooq.SQLDialect;
import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.sybase.SybaseDataType;
import org.jooq.util.sybase.sys.Sys;
import org.jooq.util.sybase.sys.tables.records.SysidxcolRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class Sysidxcol extends TableImpl<SysidxcolRecord> {

	private static final long serialVersionUID = 533651414;

	/**
	 * The singleton instance of SYSIDXCOL
	 */
	public static final Sysidxcol SYSIDXCOL = new Sysidxcol();

	/**
	 * The class holding records for this type
	 */
	private static final Class<SysidxcolRecord> __RECORD_TYPE = SysidxcolRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SysidxcolRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxcolRecord, Integer> TABLE_ID = new TableFieldImpl<SysidxcolRecord, Integer>(SQLDialect.SYBASE, "table_id", SybaseDataType.UNSIGNEDINT, SYSIDXCOL);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxcolRecord, Integer> INDEX_ID = new TableFieldImpl<SysidxcolRecord, Integer>(SQLDialect.SYBASE, "index_id", SybaseDataType.UNSIGNEDINT, SYSIDXCOL);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxcolRecord, Integer> SEQUENCE = new TableFieldImpl<SysidxcolRecord, Integer>(SQLDialect.SYBASE, "sequence", SybaseDataType.SMALLINT, SYSIDXCOL);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxcolRecord, Integer> COLUMN_ID = new TableFieldImpl<SysidxcolRecord, Integer>(SQLDialect.SYBASE, "column_id", SybaseDataType.UNSIGNEDINT, SYSIDXCOL);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxcolRecord, String> ORDER = new TableFieldImpl<SysidxcolRecord, String>(SQLDialect.SYBASE, "order", SybaseDataType.CHAR, SYSIDXCOL);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysidxcolRecord, Integer> PRIMARY_COLUMN_ID = new TableFieldImpl<SysidxcolRecord, Integer>(SQLDialect.SYBASE, "primary_column_id", SybaseDataType.UNSIGNEDINT, SYSIDXCOL);

	/**
	 * No further instances allowed
	 */
	private Sysidxcol() {
		super(SQLDialect.SYBASE, "SYSIDXCOL", Sys.SYS);
	}
}
