/**
 * This class is generated by jOOQ
 */
package org.jooq.test.oracle.generatedclasses.udt;


import javax.annotation.Generated;

import org.jooq.SQLDialect;
import org.jooq.UDTField;
import org.jooq.impl.UDTFieldImpl;
import org.jooq.impl.UDTImpl;
import org.jooq.test.oracle.generatedclasses.Test;
import org.jooq.test.oracle.generatedclasses.udt.records.UStreetTypeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class UStreetType extends UDTImpl<UStreetTypeRecord> {

	private static final long serialVersionUID = -546556286;

	/**
	 * The singleton instance of U_STREET_TYPE
	 */
	public static final UStreetType U_STREET_TYPE = new UStreetType();

	/**
	 * The class holding records for this type
	 */
	private static final Class<UStreetTypeRecord> __RECORD_TYPE = UStreetTypeRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UStreetTypeRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final UDTField<UStreetTypeRecord, String> STREET = new UDTFieldImpl<UStreetTypeRecord, String>(SQLDialect.ORACLE, "STREET", String.class, U_STREET_TYPE);

	/**
	 * An uncommented item
	 */
	public static final UDTField<UStreetTypeRecord, String> NO = new UDTFieldImpl<UStreetTypeRecord, String>(SQLDialect.ORACLE, "NO", String.class, U_STREET_TYPE);

	/**
	 * No further instances allowed
	 */
	private UStreetType() {
		super(SQLDialect.ORACLE, "U_STREET_TYPE", Test.TEST);
	}
}
