/**
 * Copyright (c) 2009-2013, Data Geekery GmbH (http://www.datageekery.com)
 * All rights reserved.
 *
 * This work is dual-licensed
 * - under the Apache Software License 2.0 (the "ASL")
 * - under the jOOQ License and Maintenance Agreement (the "jOOQ License")
 * =============================================================================
 * You may choose which license applies to you:
 *
 * - If you're using this work with Open Source databases, you may choose
 *   either ASL or jOOQ License.
 * - If you're using this work with at least one commercial database, you must
 *   choose jOOQ License
 *
 * For more information, please visit http://www.jooq.org/licenses
 *
 * Apache Software License 2.0:
 * -----------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * jOOQ License and Maintenance Agreement:
 * -----------------------------------------------------------------------------
 * Data Geekery grants the Customer the non-exclusive, timely limited and
 * non-transferable license to install and use the Software under the terms of
 * the jOOQ License and Maintenance Agreement.
 *
 * This library is distributed with a LIMITED WARRANTY. See the jOOQ License
 * and Maintenance Agreement for more details: http://www.jooq.org/licensing
 */
package org.jooq.tools.jdbc;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * A default JDBC Statement implementation delegating all JDBC 4.0 calls to an
 * internal delegate.
 *
 * @author Lukas Eder
 */
public class DefaultStatement extends JDBC41Statement implements Statement {

    private Statement delegate;

    public DefaultStatement(Statement delegate) {
        this.delegate = delegate;
    }

    public Statement getDelegate() {
        return delegate;
    }

    // ------------------------------------------------------------------------
    // XXX Executing the statement
    // ------------------------------------------------------------------------

    
    public boolean execute(String sql) throws SQLException {
        return getDelegate().execute(sql);
    }

    
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return getDelegate().execute(sql, autoGeneratedKeys);
    }

    
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return getDelegate().execute(sql, columnIndexes);
    }

    
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return getDelegate().execute(sql, columnNames);
    }

    
    public int[] executeBatch() throws SQLException {
        return getDelegate().executeBatch();
    }

    
    public ResultSet executeQuery(String sql) throws SQLException {
        return getDelegate().executeQuery(sql);
    }

    
    public int executeUpdate(String sql) throws SQLException {
        return getDelegate().executeUpdate(sql);
    }

    
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return getDelegate().executeUpdate(sql, autoGeneratedKeys);
    }

    
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return getDelegate().executeUpdate(sql, columnIndexes);
    }

    
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return getDelegate().executeUpdate(sql, columnNames);
    }

    // ------------------------------------------------------------------------
    // XXX Other methods
    // ------------------------------------------------------------------------

    
    public <T> T unwrap(Class<T> iface) throws SQLException {
        return delegate.unwrap(iface);
    }

    
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return delegate.isWrapperFor(iface);
    }

    
    public void close() throws SQLException {
        delegate.close();
    }

    
    public int getMaxFieldSize() throws SQLException {
        return delegate.getMaxFieldSize();
    }

    
    public void setMaxFieldSize(int max) throws SQLException {
        delegate.setMaxFieldSize(max);
    }

    
    public int getMaxRows() throws SQLException {
        return delegate.getMaxRows();
    }

    
    public void setMaxRows(int max) throws SQLException {
        delegate.setMaxRows(max);
    }

    
    public void setEscapeProcessing(boolean enable) throws SQLException {
        delegate.setEscapeProcessing(enable);
    }

    
    public int getQueryTimeout() throws SQLException {
        return delegate.getQueryTimeout();
    }

    
    public void setQueryTimeout(int seconds) throws SQLException {
        delegate.setQueryTimeout(seconds);
    }

    
    public void cancel() throws SQLException {
        delegate.cancel();
    }

    
    public SQLWarning getWarnings() throws SQLException {
        return delegate.getWarnings();
    }

    
    public void clearWarnings() throws SQLException {
        delegate.clearWarnings();
    }

    
    public void setCursorName(String name) throws SQLException {
        delegate.setCursorName(name);
    }

    
    public ResultSet getResultSet() throws SQLException {
        return delegate.getResultSet();
    }

    
    public int getUpdateCount() throws SQLException {
        return delegate.getUpdateCount();
    }

    
    public boolean getMoreResults() throws SQLException {
        return delegate.getMoreResults();
    }

    
    public void setFetchDirection(int direction) throws SQLException {
        delegate.setFetchDirection(direction);
    }

    
    public int getFetchDirection() throws SQLException {
        return delegate.getFetchDirection();
    }

    
    public void setFetchSize(int rows) throws SQLException {
        delegate.setFetchSize(rows);
    }

    
    public int getFetchSize() throws SQLException {
        return delegate.getFetchSize();
    }

    
    public int getResultSetConcurrency() throws SQLException {
        return delegate.getResultSetConcurrency();
    }

    
    public int getResultSetType() throws SQLException {
        return delegate.getResultSetType();
    }

    
    public void addBatch(String sql) throws SQLException {
        delegate.addBatch(sql);
    }

    
    public void clearBatch() throws SQLException {
        delegate.clearBatch();
    }

    
    public Connection getConnection() throws SQLException {
        return delegate.getConnection();
    }

    
    public boolean getMoreResults(int current) throws SQLException {
        return delegate.getMoreResults(current);
    }

    
    public ResultSet getGeneratedKeys() throws SQLException {
        return delegate.getGeneratedKeys();
    }

    
    public int getResultSetHoldability() throws SQLException {
        return delegate.getResultSetHoldability();
    }

    
    public boolean isClosed() throws SQLException {
        return delegate.isClosed();
    }

    
    public void setPoolable(boolean poolable) throws SQLException {
        delegate.setPoolable(poolable);
    }

    
    public boolean isPoolable() throws SQLException {
        return delegate.isPoolable();
    }
}
