/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.mysql.tables.records;

import org.jooq.Result;
import org.jooq.impl.RecordImpl;
import org.jooq.util.mysql.mysql.tables.TimeZone;


/**
 * This class is generated by jOOQ.
 *
 * Time zones
 */
public class TimeZoneRecord extends RecordImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * An uncommented item
	 */
	public void setTimeZoneId(Integer value) {
		setValue(TimeZone.TIME_ZONE_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTimeZoneId() {
		return getValue(TimeZone.TIME_ZONE_ID);
	}

	/**
	 * An uncommented item
	 */
	public void setUseLeapSeconds(String value) {
		setValue(TimeZone.USE_LEAP_SECONDS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getUseLeapSeconds() {
		return getValue(TimeZone.USE_LEAP_SECONDS);
	}

	public TimeZoneRecord(Result result) {
		super(result);
	}
}
