/**
 * This class is generated by jOOQ
 */
package org.jooq.test.generatedclasses.procedures;

import org.jooq.impl.ProcedureParameter;
import org.jooq.impl.StoredProcedureImpl;


/**
 * This class is generated by jOOQ.
 *
 * Check existence of an author
 */
public class PAuthorExists extends StoredProcedureImpl {

	private static final long serialVersionUID = 4909078543199362318L;


	/**
	 * An uncommented item
	 */
	public static final ProcedureParameter<String> AUTHOR_NAME = new ProcedureParameter<String>("author_name", String.class);

	/**
	 * An uncommented item
	 */
	public static final ProcedureParameter<Boolean> RESULT = new ProcedureParameter<Boolean>("result", Boolean.class);

	/**
	 * No further instances allowed
	 */
	public PAuthorExists() {
		super("p_author_exists");

		addInParameter(AUTHOR_NAME);
		addOutParameter(RESULT);
	}

	public void setAuthorName(String value) {
		setValue(AUTHOR_NAME, value);
	}

	public Boolean getResult() {
		return getValue(RESULT);
	}
}
