/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.metadata;

import java.lang.String;
import org.jooq.Field;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class SchemaPrivileges extends TableImpl {

	/**
	 * The singleton instance of SCHEMA_PRIVILEGES
	 */
	public static final SchemaPrivileges SCHEMA_PRIVILEGES = new SchemaPrivileges();

	/**
	 * An uncommented column
	 */
	public static final Field<String> GRANTEE = new TableFieldImpl<String>("GRANTEE", String.class, SCHEMA_PRIVILEGES);

	/**
	 * An uncommented column
	 */
	public static final Field<String> TABLE_CATALOG = new TableFieldImpl<String>("TABLE_CATALOG", String.class, SCHEMA_PRIVILEGES);

	/**
	 * An uncommented column
	 */
	public static final Field<String> TABLE_SCHEMA = new TableFieldImpl<String>("TABLE_SCHEMA", String.class, SCHEMA_PRIVILEGES);

	/**
	 * An uncommented column
	 */
	public static final Field<String> PRIVILEGE_TYPE = new TableFieldImpl<String>("PRIVILEGE_TYPE", String.class, SCHEMA_PRIVILEGES);

	/**
	 * An uncommented column
	 */
	public static final Field<String> IS_GRANTABLE = new TableFieldImpl<String>("IS_GRANTABLE", String.class, SCHEMA_PRIVILEGES);

	/**
	 * No further instances allowed
	 */
	private SchemaPrivileges() {
		super("SCHEMA_PRIVILEGES", "information_schema");
	}
}
