/**
 * This class is generated by jOOQ
 */
package org.jooq.test.sybase.generatedclasses.tables;


import javax.annotation.Generated;

import org.jooq.SQLDialect;
import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.test.sybase.generatedclasses.Dba;
import org.jooq.test.sybase.generatedclasses.tables.records.VBookRecord;
import org.jooq.util.sybase.SybaseDataType;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class VBook extends TableImpl<VBookRecord> {

	private static final long serialVersionUID = 283798541;

	/**
	 * The singleton instance of v_book
	 */
	public static final VBook V_BOOK = new VBook();

	/**
	 * The class holding records for this type
	 */
	private static final Class<VBookRecord> __RECORD_TYPE = VBookRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<VBookRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, Integer> ID = new TableFieldImpl<VBookRecord, Integer>(SQLDialect.SYBASE, "ID", SybaseDataType.INTEGER, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, Integer> AUTHOR_ID = new TableFieldImpl<VBookRecord, Integer>(SQLDialect.SYBASE, "AUTHOR_ID", SybaseDataType.INTEGER, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, Integer> CO_AUTHOR_ID = new TableFieldImpl<VBookRecord, Integer>(SQLDialect.SYBASE, "CO_AUTHOR_ID", SybaseDataType.INTEGER, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, Integer> DETAILS_ID = new TableFieldImpl<VBookRecord, Integer>(SQLDialect.SYBASE, "DETAILS_ID", SybaseDataType.INTEGER, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, String> TITLE = new TableFieldImpl<VBookRecord, String>(SQLDialect.SYBASE, "TITLE", SybaseDataType.VARCHAR, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, Integer> PUBLISHED_IN = new TableFieldImpl<VBookRecord, Integer>(SQLDialect.SYBASE, "PUBLISHED_IN", SybaseDataType.INTEGER, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, Integer> LANGUAGE_ID = new TableFieldImpl<VBookRecord, Integer>(SQLDialect.SYBASE, "LANGUAGE_ID", SybaseDataType.INTEGER, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, String> CONTENT_TEXT = new TableFieldImpl<VBookRecord, String>(SQLDialect.SYBASE, "CONTENT_TEXT", SybaseDataType.LONGVARCHAR, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final TableField<VBookRecord, byte[]> CONTENT_PDF = new TableFieldImpl<VBookRecord, byte[]>(SQLDialect.SYBASE, "CONTENT_PDF", SybaseDataType.LONGBINARY, V_BOOK);

	/**
	 * No further instances allowed
	 */
	private VBook() {
		super(SQLDialect.SYBASE, "v_book", Dba.DBA);
	}
}
