/**
 * This class is generated by jOOQ
 */
package org.jooq.util.derby.sys.tables.records;


import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.TableRecordImpl;
import org.jooq.util.derby.sys.tables.Sysconstraints;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class SysconstraintsRecord extends TableRecordImpl<SysconstraintsRecord> {

	private static final long serialVersionUID = 1149134765;

	/**
	 * An uncommented item
	 */
	public void setConstraintid(String value) {
		setValue(Sysconstraints.CONSTRAINTID, value);
	}

	/**
	 * An uncommented item
	 */
	public String getConstraintid() {
		return getValue(Sysconstraints.CONSTRAINTID);
	}

	/**
	 * An uncommented item
	 */
	public void setTableid(String value) {
		setValue(Sysconstraints.TABLEID, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTableid() {
		return getValue(Sysconstraints.TABLEID);
	}

	/**
	 * An uncommented item
	 */
	public void setConstraintname(String value) {
		setValue(Sysconstraints.CONSTRAINTNAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getConstraintname() {
		return getValue(Sysconstraints.CONSTRAINTNAME);
	}

	/**
	 * An uncommented item
	 */
	public void setType(String value) {
		setValue(Sysconstraints.TYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getType() {
		return getValue(Sysconstraints.TYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setSchemaid(String value) {
		setValue(Sysconstraints.SCHEMAID, value);
	}

	/**
	 * An uncommented item
	 */
	public String getSchemaid() {
		return getValue(Sysconstraints.SCHEMAID);
	}

	/**
	 * An uncommented item
	 */
	public void setState(String value) {
		setValue(Sysconstraints.STATE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getState() {
		return getValue(Sysconstraints.STATE);
	}

	/**
	 * An uncommented item
	 */
	public void setReferencecount(Integer value) {
		setValue(Sysconstraints.REFERENCECOUNT, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getReferencecount() {
		return getValue(Sysconstraints.REFERENCECOUNT);
	}

	public SysconstraintsRecord(Configuration configuration) {
		super(configuration, Sysconstraints.SYSCONSTRAINTS);
	}
}
