/**
 * This class is generated by jOOQ
 */
package org.jooq.util.oracle.sys.tables;

import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.oracle.sys.Sys;
import org.jooq.util.oracle.sys.tables.records.AllTabCommentsRecord;


/**
 * This class is generated by jOOQ.
 *
 * Comments on tables and views accessible to the user
 */
public class AllTabComments extends TableImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * The singleton instance of ALL_TAB_COMMENTS
	 */
	public static final AllTabComments ALL_TAB_COMMENTS = new AllTabComments();

	/**
	 * The class holding records for this table
	 */
	private static final Class<AllTabCommentsRecord> RECORD_TYPE = AllTabCommentsRecord.class;

	/**
	 * The class holding records for this table
	 */
	@Override
	public Class<AllTabCommentsRecord> getRecordType() {
		return RECORD_TYPE;
	}

	/**
	 * Owner of the object
	 */
	public static final TableField<String> OWNER = new TableFieldImpl<String>("OWNER", String.class, ALL_TAB_COMMENTS);

	/**
	 * Name of the object
	 */
	public static final TableField<String> TABLE_NAME = new TableFieldImpl<String>("TABLE_NAME", String.class, ALL_TAB_COMMENTS);

	/**
	 * Type of the object
	 */
	public static final TableField<String> TABLE_TYPE = new TableFieldImpl<String>("TABLE_TYPE", String.class, ALL_TAB_COMMENTS);

	/**
	 * Comment on the object
	 */
	public static final TableField<String> COMMENTS = new TableFieldImpl<String>("COMMENTS", String.class, ALL_TAB_COMMENTS);

	/**
	 * No further instances allowed
	 */
	private AllTabComments() {
		super("ALL_TAB_COMMENTS", Sys.SYS);
	}
}
