/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.mysql.tables;

import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.mysql.mysql.Mysql;


/**
 * This class is generated by jOOQ.
 *
 * help topics
 */
public class HelpTopic extends TableImpl {

	private static final long serialVersionUID = 6965032640133229628L;

	/**
	 * The singleton instance of help_topic
	 */
	public static final HelpTopic HELP_TOPIC = new HelpTopic();

	/**
	 * An uncommented item
	 */
	public static final TableField<Integer> HELP_TOPIC_ID = new TableFieldImpl<Integer>("help_topic_id", Integer.class, HELP_TOPIC);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> NAME = new TableFieldImpl<String>("name", String.class, HELP_TOPIC);

	/**
	 * An uncommented item
	 */
	public static final TableField<Short> HELP_CATEGORY_ID = new TableFieldImpl<Short>("help_category_id", Short.class, HELP_TOPIC);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> DESCRIPTION = new TableFieldImpl<String>("description", String.class, HELP_TOPIC);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> EXAMPLE = new TableFieldImpl<String>("example", String.class, HELP_TOPIC);

	/**
	 * An uncommented item
	 */
	public static final TableField<String> URL = new TableFieldImpl<String>("url", String.class, HELP_TOPIC);

	/**
	 * No further instances allowed
	 */
	private HelpTopic() {
		super("help_topic", Mysql.MYSQL);
	}
}
