/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.mysql.tables;

import org.jooq.Field;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 *
 * Database privileges
 */
public class Db extends TableImpl {

	private static final long serialVersionUID = -1255499406514859091L;

	/**
	 * The singleton instance of db
	 */
	public static final Db DB = new Db();

	/**
	 * An uncommented item
	 */
	public static final Field<String> HOST = new TableFieldImpl<String>("Host", String.class, DB);

	/**
	 * An uncommented item
	 * 
	 * This item has the same name as its container. That is why an underline character was appended to the Java field name
	 */
	public static final Field<String> DB_ = new TableFieldImpl<String>("Db", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> USER = new TableFieldImpl<String>("User", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> SELECT_PRIV = new TableFieldImpl<String>("Select_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> INSERT_PRIV = new TableFieldImpl<String>("Insert_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> UPDATE_PRIV = new TableFieldImpl<String>("Update_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> DELETE_PRIV = new TableFieldImpl<String>("Delete_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> CREATE_PRIV = new TableFieldImpl<String>("Create_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> DROP_PRIV = new TableFieldImpl<String>("Drop_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> GRANT_PRIV = new TableFieldImpl<String>("Grant_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> REFERENCES_PRIV = new TableFieldImpl<String>("References_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> INDEX_PRIV = new TableFieldImpl<String>("Index_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> ALTER_PRIV = new TableFieldImpl<String>("Alter_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> CREATE_TMP_TABLE_PRIV = new TableFieldImpl<String>("Create_tmp_table_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> LOCK_TABLES_PRIV = new TableFieldImpl<String>("Lock_tables_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> CREATE_VIEW_PRIV = new TableFieldImpl<String>("Create_view_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> SHOW_VIEW_PRIV = new TableFieldImpl<String>("Show_view_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> CREATE_ROUTINE_PRIV = new TableFieldImpl<String>("Create_routine_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> ALTER_ROUTINE_PRIV = new TableFieldImpl<String>("Alter_routine_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> EXECUTE_PRIV = new TableFieldImpl<String>("Execute_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> EVENT_PRIV = new TableFieldImpl<String>("Event_priv", String.class, DB);

	/**
	 * An uncommented item
	 */
	public static final Field<String> TRIGGER_PRIV = new TableFieldImpl<String>("Trigger_priv", String.class, DB);

	/**
	 * No further instances allowed
	 */
	private Db() {
		super("db", "mysql");
	}
}
