/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.mysql.tables;

import org.jooq.Field;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 *
 * Time zone transitions
 */
public class TimeZoneTransition extends TableImpl {

	private static final long serialVersionUID = -3609783575536065142L;

	/**
	 * The singleton instance of time_zone_transition
	 */
	public static final TimeZoneTransition TIME_ZONE_TRANSITION = new TimeZoneTransition();

	/**
	 * An uncommented item
	 */
	public static final Field<Integer> TIME_ZONE_ID = new TableFieldImpl<Integer>("Time_zone_id", Integer.class, TIME_ZONE_TRANSITION);

	/**
	 * An uncommented item
	 */
	public static final Field<Integer> TRANSITION_TIME = new TableFieldImpl<Integer>("Transition_time", Integer.class, TIME_ZONE_TRANSITION);

	/**
	 * An uncommented item
	 */
	public static final Field<Integer> TRANSITION_TYPE_ID = new TableFieldImpl<Integer>("Transition_type_id", Integer.class, TIME_ZONE_TRANSITION);

	/**
	 * No further instances allowed
	 */
	private TimeZoneTransition() {
		super("time_zone_transition", "mysql");
	}
}
