/**
 * This class is generated by jOOQ
 */
package org.jooq.util.oracle.sys.tables;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.TableField;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.oracle.sys.Sys;
import org.jooq.util.oracle.sys.tables.records.AllSequencesRecord;


/**
 * This class is generated by jOOQ.
 *
 * Description of SEQUENCEs accessible to the user
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class AllSequences extends TableImpl<AllSequencesRecord> {

	private static final long serialVersionUID = 927914927;

	/**
	 * The singleton instance of ALL_SEQUENCES
	 */
	public static final AllSequences ALL_SEQUENCES = new AllSequences();

	/**
	 * The class holding records for this type
	 */
	private static final Class<AllSequencesRecord> __RECORD_TYPE = AllSequencesRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AllSequencesRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * Name of the owner of the sequence
	 */
	public static final TableField<AllSequencesRecord, String> SEQUENCE_OWNER = new TableFieldImpl<AllSequencesRecord, String>("SEQUENCE_OWNER", SQLDataType.VARCHAR, ALL_SEQUENCES);

	/**
	 * SEQUENCE name
	 */
	public static final TableField<AllSequencesRecord, String> SEQUENCE_NAME = new TableFieldImpl<AllSequencesRecord, String>("SEQUENCE_NAME", SQLDataType.VARCHAR, ALL_SEQUENCES);

	/**
	 * Minimum value of the sequence
	 */
	public static final TableField<AllSequencesRecord, BigDecimal> MIN_VALUE = new TableFieldImpl<AllSequencesRecord, BigDecimal>("MIN_VALUE", SQLDataType.NUMERIC, ALL_SEQUENCES);

	/**
	 * Maximum value of the sequence
	 */
	public static final TableField<AllSequencesRecord, BigDecimal> MAX_VALUE = new TableFieldImpl<AllSequencesRecord, BigDecimal>("MAX_VALUE", SQLDataType.NUMERIC, ALL_SEQUENCES);

	/**
	 * Value by which sequence is incremented
	 */
	public static final TableField<AllSequencesRecord, BigDecimal> INCREMENT_BY = new TableFieldImpl<AllSequencesRecord, BigDecimal>("INCREMENT_BY", SQLDataType.NUMERIC, ALL_SEQUENCES);

	/**
	 * Does sequence wrap around on reaching limit?
	 */
	public static final TableField<AllSequencesRecord, String> CYCLE_FLAG = new TableFieldImpl<AllSequencesRecord, String>("CYCLE_FLAG", SQLDataType.VARCHAR, ALL_SEQUENCES);

	/**
	 * Are sequence numbers generated in order?
	 */
	public static final TableField<AllSequencesRecord, String> ORDER_FLAG = new TableFieldImpl<AllSequencesRecord, String>("ORDER_FLAG", SQLDataType.VARCHAR, ALL_SEQUENCES);

	/**
	 * Number of sequence numbers to cache
	 */
	public static final TableField<AllSequencesRecord, BigDecimal> CACHE_SIZE = new TableFieldImpl<AllSequencesRecord, BigDecimal>("CACHE_SIZE", SQLDataType.NUMERIC, ALL_SEQUENCES);

	/**
	 * Last sequence number written to disk
	 */
	public static final TableField<AllSequencesRecord, BigDecimal> LAST_NUMBER = new TableFieldImpl<AllSequencesRecord, BigDecimal>("LAST_NUMBER", SQLDataType.NUMERIC, ALL_SEQUENCES);

	/**
	 * No further instances allowed
	 */
	private AllSequences() {
		super("ALL_SEQUENCES", Sys.SYS);
	}
}
