/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.mysql;


import javax.annotation.Generated;

import org.jooq.SQLDialect;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class Mysql extends SchemaImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * The singleton instance of mysql
	 */
	public static final Mysql MYSQL = new Mysql();

	/**
	 * No further instances allowed
	 */
	private Mysql() {
		super(SQLDialect.MYSQL, "mysql");
	}
}
