/**
 * This class is generated by jOOQ
 */
package org.jooq.test.mysql.generatedclasses;


import java.sql.Connection;
import java.sql.SQLException;

import javax.annotation.Generated;

import org.jooq.test.mysql.generatedclasses.procedures.PAuthorExists;
import org.jooq.test.mysql.generatedclasses.procedures.PCreateAuthor;
import org.jooq.test.mysql.generatedclasses.procedures.PCreateAuthorByName;
import org.jooq.test.mysql.generatedclasses.procedures.PUnused;


/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all stored procedures in test
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public final class Procedures {

	/**
	 * Invoke P_AUTHOR_EXISTS
	 *
	 * @param authorName IN parameter
	 * @param result OUT parameter
	 */
	public static Integer pAuthorExists(Connection connection, String authorName) throws SQLException {
		PAuthorExists p = new PAuthorExists();
		p.setAuthorName(authorName);

		p.execute(connection);
		return p.getResult();
	}

	/**
	 * Invoke P_CREATE_AUTHOR
	 *
	 */
	public static void pCreateAuthor(Connection connection) throws SQLException {
		PCreateAuthor p = new PCreateAuthor();

		p.execute(connection);
	}

	/**
	 * Invoke P_CREATE_AUTHOR_BY_NAME
	 *
	 * @param firstName IN parameter
	 * @param lastName IN parameter
	 */
	public static void pCreateAuthorByName(Connection connection, String firstName, String lastName) throws SQLException {
		PCreateAuthorByName p = new PCreateAuthorByName();
		p.setFirstName(firstName);
		p.setLastName(lastName);

		p.execute(connection);
	}

	/**
	 * Invoke P_UNUSED
	 *
	 * @param in1 IN parameter
	 * @param out1 OUT parameter
	 * @param out2 IN OUT parameter
	 */
	public static PUnused pUnused(Connection connection, String in1, Boolean out2) throws SQLException {
		PUnused p = new PUnused();
		p.setIn1(in1);
		p.setOut2(out2);

		p.execute(connection);
		return p;
	}

	/**
	 * No instances
	 */
	private Procedures() {}
}
