/**
 * This class is generated by jOOQ
 */
package org.jooq.test.mysql.generatedclasses;


import javax.annotation.Generated;

import org.jooq.SQLDialect;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class Test extends SchemaImpl {

	private static final long serialVersionUID = 114029604;

	/**
	 * The singleton instance of test
	 */
	public static final Test TEST = new Test();

	/**
	 * No further instances allowed
	 */
	private Test() {
		super(SQLDialect.MYSQL, "test");
	}
}
