/**
 * This class is generated by jOOQ
 */
package org.jooq.util.postgres.pg_catalog.functions;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.SQLDialect;
import org.jooq.Select;
import org.jooq.impl.ParameterImpl;
import org.jooq.impl.StoredFunctionImpl;
import org.jooq.util.postgres.PostgresDataType;
import org.jooq.util.postgres.pg_catalog.PgCatalog;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class FormatType extends StoredFunctionImpl<String> {

	private static final long serialVersionUID = -770964658;


	/**
	 * An uncommented item
	 */
	public static final Parameter<Long> _1 = new ParameterImpl<Long>(SQLDialect.POSTGRES, "_1", PostgresDataType.OID);

	/**
	 * An uncommented item
	 */
	public static final Parameter<Integer> _2 = new ParameterImpl<Integer>(SQLDialect.POSTGRES, "_2", PostgresDataType.INTEGER);

	/**
	 * No further instances allowed
	 */
	public FormatType() {
		super(SQLDialect.POSTGRES, "format_type", PgCatalog.PG_CATALOG, PostgresDataType.TEXT);

		addInParameter(_1);
		addInParameter(_2);
	}

	/**
	 * Set the <code>_1</code> parameter to the function
	 */
	public void set__1(Long value) {
		setValue(_1, value);
	}

	/**
	 * Set the <code>_1</code> parameter to the function
	 * <p>
	 * Use this method only, if the function is called as a {@link Field} in a {@link Select} statement!
	 */
	public void set__1(Field<Long> field) {
		setField(_1, field);
	}

	/**
	 * Set the <code>_2</code> parameter to the function
	 */
	public void set__2(Integer value) {
		setValue(_2, value);
	}

	/**
	 * Set the <code>_2</code> parameter to the function
	 * <p>
	 * Use this method only, if the function is called as a {@link Field} in a {@link Select} statement!
	 */
	public void set__2(Field<Integer> field) {
		setField(_2, field);
	}
}
