/**
 * This class is generated by jOOQ
 */
package org.jooq.util.postgres.pg_catalog.tables;


import javax.annotation.Generated;

import org.jooq.TableField;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.postgres.pg_catalog.PgCatalog;
import org.jooq.util.postgres.pg_catalog.tables.records.PgClassRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class PgClass extends TableImpl<PgClassRecord> {

	private static final long serialVersionUID = 1800757010;

	/**
	 * The singleton instance of pg_class
	 */
	public static final PgClass PG_CLASS = new PgClass();

	/**
	 * The class holding records for this type
	 */
	private static final Class<PgClassRecord> __RECORD_TYPE = PgClassRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PgClassRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, String> RELNAME = new TableFieldImpl<PgClassRecord, String>("relname", SQLDataType.VARCHAR, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Long> RELNAMESPACE = new TableFieldImpl<PgClassRecord, Long>("relnamespace", SQLDataType.BIGINT, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Long> RELTYPE = new TableFieldImpl<PgClassRecord, Long>("reltype", SQLDataType.BIGINT, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Long> RELOFTYPE = new TableFieldImpl<PgClassRecord, Long>("reloftype", SQLDataType.BIGINT, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Long> RELOWNER = new TableFieldImpl<PgClassRecord, Long>("relowner", SQLDataType.BIGINT, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Long> RELAM = new TableFieldImpl<PgClassRecord, Long>("relam", SQLDataType.BIGINT, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Long> RELFILENODE = new TableFieldImpl<PgClassRecord, Long>("relfilenode", SQLDataType.BIGINT, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Long> RELTABLESPACE = new TableFieldImpl<PgClassRecord, Long>("reltablespace", SQLDataType.BIGINT, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Integer> RELPAGES = new TableFieldImpl<PgClassRecord, Integer>("relpages", SQLDataType.INTEGER, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Float> RELTUPLES = new TableFieldImpl<PgClassRecord, Float>("reltuples", SQLDataType.REAL, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Long> RELTOASTRELID = new TableFieldImpl<PgClassRecord, Long>("reltoastrelid", SQLDataType.BIGINT, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Long> RELTOASTIDXID = new TableFieldImpl<PgClassRecord, Long>("reltoastidxid", SQLDataType.BIGINT, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Boolean> RELHASINDEX = new TableFieldImpl<PgClassRecord, Boolean>("relhasindex", SQLDataType.BOOLEAN, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Boolean> RELISSHARED = new TableFieldImpl<PgClassRecord, Boolean>("relisshared", SQLDataType.BOOLEAN, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Boolean> RELISTEMP = new TableFieldImpl<PgClassRecord, Boolean>("relistemp", SQLDataType.BOOLEAN, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, String> RELKIND = new TableFieldImpl<PgClassRecord, String>("relkind", SQLDataType.CHAR, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Short> RELNATTS = new TableFieldImpl<PgClassRecord, Short>("relnatts", SQLDataType.SMALLINT, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Short> RELCHECKS = new TableFieldImpl<PgClassRecord, Short>("relchecks", SQLDataType.SMALLINT, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Boolean> RELHASOIDS = new TableFieldImpl<PgClassRecord, Boolean>("relhasoids", SQLDataType.BOOLEAN, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Boolean> RELHASPKEY = new TableFieldImpl<PgClassRecord, Boolean>("relhaspkey", SQLDataType.BOOLEAN, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Boolean> RELHASEXCLUSION = new TableFieldImpl<PgClassRecord, Boolean>("relhasexclusion", SQLDataType.BOOLEAN, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Boolean> RELHASRULES = new TableFieldImpl<PgClassRecord, Boolean>("relhasrules", SQLDataType.BOOLEAN, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Boolean> RELHASTRIGGERS = new TableFieldImpl<PgClassRecord, Boolean>("relhastriggers", SQLDataType.BOOLEAN, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Boolean> RELHASSUBCLASS = new TableFieldImpl<PgClassRecord, Boolean>("relhassubclass", SQLDataType.BOOLEAN, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, Long> RELFROZENXID = new TableFieldImpl<PgClassRecord, Long>("relfrozenxid", SQLDataType.BIGINT, PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, String[]> RELACL = new TableFieldImpl<PgClassRecord, String[]>("relacl", SQLDataType.VARCHAR.getArrayDataType(), PG_CLASS);

	/**
	 * An uncommented item
	 */
	public static final TableField<PgClassRecord, String[]> RELOPTIONS = new TableFieldImpl<PgClassRecord, String[]>("reloptions", SQLDataType.CLOB.getArrayDataType(), PG_CLASS);

	/**
	 * No further instances allowed
	 */
	private PgClass() {
		super("pg_class", PgCatalog.PG_CATALOG);
	}
}
