/**
 * This class is generated by jOOQ
 */
package org.jooq.test.hsqldb.generatedclasses.tables.records;


import org.jooq.Configuration;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.test.hsqldb.generatedclasses.tables.XTestCase71;


/**
 * This class is generated by jOOQ.
 */
public class XTestCase71Record extends UpdatableRecordImpl<XTestCase71Record> {

	private static final long serialVersionUID = 1L;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(Integer value) {
		setValue(XTestCase71.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public Integer getId() {
		return getValue(XTestCase71.ID);
	}

	/**
	 * An uncommented item
	 * 
	 * FOREIGN KEY [PUBLIC.X_TEST_CASE_71.TEST_CASE_64_69_ID] REFERENCES X_TEST_CASE_64_69 [PUBLIC.X_TEST_CASE_64_69.ID]
	 */
	public void setTestCase6469Id(Short value) {
		setValue(XTestCase71.TEST_CASE_64_69_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * FOREIGN KEY [PUBLIC.X_TEST_CASE_71.TEST_CASE_64_69_ID] REFERENCES X_TEST_CASE_64_69 [PUBLIC.X_TEST_CASE_64_69.ID]
	 */
	public Short getTestCase6469Id() {
		return getValue(XTestCase71.TEST_CASE_64_69_ID);
	}

	public XTestCase71Record(Configuration configuration) {
		super(configuration, XTestCase71.X_TEST_CASE_71);
	}
}
