/**
 * This class is generated by jOOQ
 */
package org.jooq.test.postgres.generatedclasses.tables.records;


import org.jooq.Configuration;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.test.postgres.generatedclasses.tables.XTestCase71;


/**
 * This class is generated by jOOQ.
 */
public class XTestCase71Record extends UpdatableRecordImpl<XTestCase71Record> {

	private static final long serialVersionUID = 1L;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(Integer value) {
		setValue(XTestCase71.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public Integer getId() {
		return getValue(XTestCase71.ID);
	}

	/**
	 * An uncommented item
	 * 
	 * FOREIGN KEY [public.x_test_case_71.test_case_64_69_id] REFERENCES x_test_case_64_69 [public.x_test_case_64_69.id]
	 */
	public void setTestCase6469Id(Short value) {
		setValue(XTestCase71.TEST_CASE_64_69_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * FOREIGN KEY [public.x_test_case_71.test_case_64_69_id] REFERENCES x_test_case_64_69 [public.x_test_case_64_69.id]
	 */
	public Short getTestCase6469Id() {
		return getValue(XTestCase71.TEST_CASE_64_69_ID);
	}

	public XTestCase71Record(Configuration configuration) {
		super(configuration, XTestCase71.X_TEST_CASE_71);
	}
}
