/**
 * This class is generated by jOOQ
 */
package org.jooq.test.postgres.generatedclasses.tables.records;


import org.jooq.Configuration;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.test.postgres.generatedclasses.tables.XUnused_2;


/**
 * This class is generated by jOOQ.
 */
public class XUnused_2Record extends UpdatableRecordImpl<XUnused_2Record> {

	private static final long serialVersionUID = 1L;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(Integer value) {
		setValue(XUnused_2.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public Integer getId() {
		return getValue(XUnused_2.ID);
	}

	/**
	 * An uncommented item
	 */
	public void setUnusedId(Integer value) {
		setValue(XUnused_2.UNUSED_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getUnusedId() {
		return getValue(XUnused_2.UNUSED_ID);
	}

	public XUnused_2Record(Configuration configuration) {
		super(configuration, XUnused_2.X_UNUSED_2);
	}
}
