/**
 * This class is generated by jOOQ
 */
package org.jooq.util.postgres.information_schema.tables;


import javax.annotation.Generated;

import org.jooq.TableField;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.postgres.information_schema.InformationSchema;
import org.jooq.util.postgres.information_schema.tables.records.AttributesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class Attributes extends TableImpl<AttributesRecord> {

	private static final long serialVersionUID = -2064216151;

	/**
	 * The singleton instance of attributes
	 */
	public static final Attributes ATTRIBUTES = new Attributes();

	/**
	 * The class holding records for this type
	 */
	private static final Class<AttributesRecord> __RECORD_TYPE = AttributesRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AttributesRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> UDT_CATALOG = new TableFieldImpl<AttributesRecord, String>("udt_catalog", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> UDT_SCHEMA = new TableFieldImpl<AttributesRecord, String>("udt_schema", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> UDT_NAME = new TableFieldImpl<AttributesRecord, String>("udt_name", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> ATTRIBUTE_NAME = new TableFieldImpl<AttributesRecord, String>("attribute_name", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, Integer> ORDINAL_POSITION = new TableFieldImpl<AttributesRecord, Integer>("ordinal_position", SQLDataType.INTEGER, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> ATTRIBUTE_DEFAULT = new TableFieldImpl<AttributesRecord, String>("attribute_default", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> IS_NULLABLE = new TableFieldImpl<AttributesRecord, String>("is_nullable", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> DATA_TYPE = new TableFieldImpl<AttributesRecord, String>("data_type", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, Integer> CHARACTER_MAXIMUM_LENGTH = new TableFieldImpl<AttributesRecord, Integer>("character_maximum_length", SQLDataType.INTEGER, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, Integer> CHARACTER_OCTET_LENGTH = new TableFieldImpl<AttributesRecord, Integer>("character_octet_length", SQLDataType.INTEGER, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> CHARACTER_SET_CATALOG = new TableFieldImpl<AttributesRecord, String>("character_set_catalog", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> CHARACTER_SET_SCHEMA = new TableFieldImpl<AttributesRecord, String>("character_set_schema", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> CHARACTER_SET_NAME = new TableFieldImpl<AttributesRecord, String>("character_set_name", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> COLLATION_CATALOG = new TableFieldImpl<AttributesRecord, String>("collation_catalog", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> COLLATION_SCHEMA = new TableFieldImpl<AttributesRecord, String>("collation_schema", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> COLLATION_NAME = new TableFieldImpl<AttributesRecord, String>("collation_name", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, Integer> NUMERIC_PRECISION = new TableFieldImpl<AttributesRecord, Integer>("numeric_precision", SQLDataType.INTEGER, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, Integer> NUMERIC_PRECISION_RADIX = new TableFieldImpl<AttributesRecord, Integer>("numeric_precision_radix", SQLDataType.INTEGER, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, Integer> NUMERIC_SCALE = new TableFieldImpl<AttributesRecord, Integer>("numeric_scale", SQLDataType.INTEGER, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, Integer> DATETIME_PRECISION = new TableFieldImpl<AttributesRecord, Integer>("datetime_precision", SQLDataType.INTEGER, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> INTERVAL_TYPE = new TableFieldImpl<AttributesRecord, String>("interval_type", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> INTERVAL_PRECISION = new TableFieldImpl<AttributesRecord, String>("interval_precision", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> ATTRIBUTE_UDT_CATALOG = new TableFieldImpl<AttributesRecord, String>("attribute_udt_catalog", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> ATTRIBUTE_UDT_SCHEMA = new TableFieldImpl<AttributesRecord, String>("attribute_udt_schema", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> ATTRIBUTE_UDT_NAME = new TableFieldImpl<AttributesRecord, String>("attribute_udt_name", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> SCOPE_CATALOG = new TableFieldImpl<AttributesRecord, String>("scope_catalog", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> SCOPE_SCHEMA = new TableFieldImpl<AttributesRecord, String>("scope_schema", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> SCOPE_NAME = new TableFieldImpl<AttributesRecord, String>("scope_name", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, Integer> MAXIMUM_CARDINALITY = new TableFieldImpl<AttributesRecord, Integer>("maximum_cardinality", SQLDataType.INTEGER, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> DTD_IDENTIFIER = new TableFieldImpl<AttributesRecord, String>("dtd_identifier", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * An uncommented item
	 */
	public static final TableField<AttributesRecord, String> IS_DERIVED_REFERENCE_ATTRIBUTE = new TableFieldImpl<AttributesRecord, String>("is_derived_reference_attribute", SQLDataType.VARCHAR, ATTRIBUTES);

	/**
	 * No further instances allowed
	 */
	private Attributes() {
		super("attributes", InformationSchema.INFORMATION_SCHEMA);
	}
}
