/**
 * Copyright (c) 2009, Lukas Eder, lukas.eder@gmail.com
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * . Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * . Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * . Neither the name of the "jOOQ" nor the names of its contributors may be
 *   used to endorse or promote products derived from this software without
 *   specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

package org.jooq;

/**
 * This intermediate interface provides a higher-level specification for
 * {@link SelectQuery} objects. This is necessary, because combined select
 * statements cannot have their select fields modified, unless the result is put
 * in an inner select construct, transforming it into a more specific
 * SelectQuery again.
 *
 * @author Lukas Eder
 */
public interface ResultProviderQuery extends Query {

	/**
	 * Return the result generated by a previous call to execute();
	 *
	 * @return The result or <code>null</code> if no call to execute() was done
	 *         previously.
	 */
	Result getResult();

	/**
	 * Combine this ResultProvider with another one, using the
	 * {@link CombineOperator#UNION} operator.
	 *
	 * @param other
	 *            The ResultProvider to combine this one with
	 * @return
	 * @see #combine(ResultProviderQuery, CombineOperator)
	 */
	ResultProviderQuery combine(ResultProviderQuery other);

	/**
	 * Combine this ResultProvider with another one, using the given operator.
	 *
	 * @param other
	 *            The ResultProvider to combine this one with
	 * @param operator
	 *            The combine operator
	 * @return
	 */
	ResultProviderQuery combine(ResultProviderQuery other, CombineOperator operator);

	/**
	 * Use this query as a table
	 * <p>
	 * This method is useful for things like
	 * <code>SELECT * FROM (SELECT * FROM x WHERE x.a = '1') WHERE
	 * @return This result provider as a Table object
	 */
	Table asTable();

	/**
	 * Use this query as a field.
	 * <p>
	 * This method is useful for things like
	 * <code>SELECT y.*, (SELECT a FROM x) a FROM y</code>
	 *
	 * @return This result provider as a Field&lt;?&gt; object
	 */
	<T> Field<T> asField();

	/**
	 * Use this query for IN conditions.
	 * <p>
	 * This method is useful for things like
	 * <code>SELECT * FROM x WHERE x.field IN (SELECT ...)</code>
	 *
	 * @param field
	 *            The field to compare this query's results with
	 * @return This result provider as a InCondition object
	 */
	<T> SubQueryCondition<T> asInCondition(Field<T> field);

	/**
	 * Use this query for NOT IN conditions.
	 * <p>
	 * This method is useful for things like
	 * <code>SELECT * FROM x WHERE x.field NOT IN (SELECT ...)</code>
	 *
	 * @param field
	 *            The field to compare this query's results with
	 * @return This result provider as a InCondition object
	 */
	<T> SubQueryCondition<T> asNotInCondition(Field<T> field);

	/**
	 * Use this query for EQUALS conditions.
	 * <p>
	 * This method is useful for things like
	 * <code>SELECT * FROM x WHERE x.field = (SELECT ...)</code>
	 *
	 * @param field
	 *            The field to compare this query's results with
	 * @return This result provider as a InCondition object
	 */
	<T> SubQueryCondition<T> asCompareCondition(Field<T> field);

	/**
	 * This method is useful for things like
	 * <code>SELECT * FROM x WHERE x.field [any operator] (SELECT ...)</code>
	 *
	 * @param field
	 *            The field to compare this query's results with
	 * @return This result provider as a InCondition object
	 */
	<T> SubQueryCondition<T> asSubQueryCondition(Field<T> field, SubQueryOperator operator);

	/**
	 * Use this query for EXISTS conditions.
	 * <p>
	 * This method is useful for things like
	 * <code>SELECT * FROM x WHERE EXISTS (SELECT ...)</code>
	 *
	 * @param field
	 *            The field to compare this query's results with
	 * @return This result provider as a InCondition object
	 */
	ExistsCondition asExistsCondition();

	/**
	 * Use this query for NOT EXISTS conditions.
	 * <p>
	 * This method is useful for things like
	 * <code>SELECT * FROM x WHERE NOT EXISTS (SELECT ...)</code>
	 *
	 * @param field
	 *            The field to compare this query's results with
	 * @return This result provider as a InCondition object
	 */
	ExistsCondition asNotExistsCondition();

	/**
	 * Adds an ordering field, ordering by the default sort order
	 *
	 * @param field The ordering field
	 */
	void addOrderBy(Field<?> field);

	/**
	 * Adds an ordering field
	 *
	 * @param field The ordering field
	 * @param order The sort order
	 */
	void addOrderBy(Field<?> field, SortOrder order);
}
