/**
 * Copyright (c) 2009-2011, Lukas Eder, lukas.eder@gmail.com
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * . Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * . Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * . Neither the name of the "jOOQ" nor the names of its contributors may be
 *   used to endorse or promote products derived from this software without
 *   specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package org.jooq;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;

/**
 * A {@link Query} that can provide a {@link Result} after execution
 *
 * @author Lukas Eder
 */
public interface Select<R extends Record> extends Query, TableLike<R>, FieldLike, FieldProvider {

    /**
     * Return the result generated by a previous call to execute();
     *
     * @return The result or <code>null</code> if no call to execute() was done
     *         previously.
     */
    Result<R> getResult();

    /**
     * Execute the query and return the generated result
     * <p>
     * This is the same as calling {@link #execute()} and then
     * {@link #getResult()}
     *
     * @return The result.
     */
    Result<R> fetch() throws SQLException;

    /**
     * Execute the query and return the generated result
     * <p>
     * The returned {@link Cursor} holds a reference to the executed
     * {@link PreparedStatement} and the associated {@link ResultSet}. Data can
     * be fetched (or iterated over) lazily, fetching records from the
     * {@link ResultSet} one by one.
     * <p>
     * Client code is responsible for closing the cursor after use.
     *
     * @return The resulting cursor.
     */
    Cursor<R> fetchLazy() throws SQLException;

    /**
     * Execute the query and return all values for a field from the generated
     * result.
     * <p>
     * This is the same as calling {@link #fetch()} and then
     * {@link Result#getValues(Field)}
     *
     * @return The resulting values.
     */
    <T> List<T> fetch(Field<T> field) throws SQLException;

    /**
     * Execute the query and return all values for a field index from the
     * generated result.
     * <p>
     * This is the same as calling {@link #fetch()} and then
     * {@link Result#getValues(int)}
     *
     * @return The resulting values.
     */
    List<?> fetch(int fieldIndex) throws SQLException;

    /**
     * Execute the query and return all values for a field name from the
     * generated result.
     * <p>
     * This is the same as calling {@link #fetch()} and then
     * {@link Result#getValues(String)}
     *
     * @return The resulting values.
     */
    List<?> fetch(String fieldName) throws SQLException;

    /**
     * Execute the query and return return at most one resulting value for a
     * field from the generated result.
     * <p>
     * This is the same as calling {@link #fetchOne()} and then
     * {@link Record#getValue(Field)}
     *
     * @return The resulting values.
     * @throws SQLException - If something went wrong executing the query or if
     *             the query returned more than one value.
     */
    <T> T fetchOne(Field<T> field) throws SQLException;

    /**
     * Execute the query and return return at most one resulting value for a
     * field index from the generated result.
     * <p>
     * This is the same as calling {@link #fetchOne()} and then
     * {@link Record#getValue(int)}
     *
     * @return The resulting values.
     * @throws SQLException - If something went wrong executing the query or if
     *             the query returned more than one value.
     */
    Object fetchOne(int fieldIndex) throws SQLException;

    /**
     * Execute the query and return return at most one resulting value for a
     * field name from the generated result.
     * <p>
     * This is the same as calling {@link #fetchOne()} and then
     * {@link Record#getValue(int)}
     *
     * @return The resulting values.
     * @throws SQLException - If something went wrong executing the query or if
     *             the query returned more than one value.
     */
    Object fetchOne(String fieldName) throws SQLException;

    /**
     * Execute the query and return at most one resulting record.
     * <p>
     *
     * @return The resulting record or <code>null</code> if the query returns no
     *         records.
     * @throws SQLException - If something went wrong executing the query or if
     *             the query returned more than one record.
     */
    R fetchOne() throws SQLException;

    /**
     * Execute the query and return at most one resulting record.
     *
     * @return The first resulting record or <code>null</code> if the query
     *         returns no records.
     */
    R fetchAny() throws SQLException;

    /**
     * Execute the query and return a {@link Map} with one of the result's
     * columns as key and the corresponding records as value.
     * <p>
     * An exception is thrown, if the key turns out to be non-unique in the
     * result set.
     *
     * @param <K> The key's generic field type
     * @param key The key field. Client code must assure that this field is
     *            unique in the result set.
     * @return A Map containing the results
     * @throws SQLException - If something went wrong executing the query or if
     *             the key field returned two or more equal values from the
     *             result set.
     */
    <K> Map<K, R> fetchMap(Field<K> key) throws SQLException;

    /**
     * Execute the query and return a {@link Map} with one of the result's
     * columns as key and another one of the result's columns as value
     * <p>
     * An exception is thrown, if the key turns out to be non-unique in the
     * result set.
     *
     * @param <K> The key's generic field type
     * @param <V> The value's generic field type
     * @param key The key field. Client code must assure that this field is
     *            unique in the result set.
     * @param value The value field
     * @return A Map containing the results
     * @throws SQLException - If something went wrong executing the query or if
     *             the key field returned two or more equal values from the
     *             result set.
     */
    <K, V> Map<K, V> fetchMap(Field<K> key, Field<V> value) throws SQLException;

    /**
     * Combine with other selects
     */
    Select<R> union(Select<R> select);

    /**
     * Combine with other selects
     */
    Select<R> unionAll(Select<R> select);

    /**
     * Combine with other selects
     */
    Select<R> except(Select<R> select);

    /**
     * Combine with other selects
     */
    Select<R> intersect(Select<R> select);

    /**
     * The record type produced by this query
     */
    Class<? extends R> getRecordType();

    /**
     * All fields selected in this query
     */
    List<Field<?>> getSelect();
}
