/**
 * This class is generated by jOOQ
 */
package org.jooq.util.db2.syscat.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;
import org.jooq.util.db2.syscat.tables.Functions;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class FunctionsRecord extends TableRecordImpl<FunctionsRecord> {

	private static final long serialVersionUID = -1710983626;

	/**
	 * An uncommented item
	 */
	public void setFuncschema(String value) {
		setValue(Functions.FUNCSCHEMA, value);
	}

	/**
	 * An uncommented item
	 */
	public String getFuncschema() {
		return getValue(Functions.FUNCSCHEMA);
	}

	/**
	 * An uncommented item
	 */
	public void setFuncname(String value) {
		setValue(Functions.FUNCNAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getFuncname() {
		return getValue(Functions.FUNCNAME);
	}

	/**
	 * An uncommented item
	 */
	public void setSpecificname(String value) {
		setValue(Functions.SPECIFICNAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getSpecificname() {
		return getValue(Functions.SPECIFICNAME);
	}

	/**
	 * An uncommented item
	 */
	public void setDefiner(String value) {
		setValue(Functions.DEFINER, value);
	}

	/**
	 * An uncommented item
	 */
	public String getDefiner() {
		return getValue(Functions.DEFINER);
	}

	/**
	 * An uncommented item
	 */
	public void setFuncid(Integer value) {
		setValue(Functions.FUNCID, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getFuncid() {
		return getValue(Functions.FUNCID);
	}

	/**
	 * An uncommented item
	 */
	public void setReturnType(Short value) {
		setValue(Functions.RETURN_TYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public Short getReturnType() {
		return getValue(Functions.RETURN_TYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setOrigin(String value) {
		setValue(Functions.ORIGIN, value);
	}

	/**
	 * An uncommented item
	 */
	public String getOrigin() {
		return getValue(Functions.ORIGIN);
	}

	/**
	 * An uncommented item
	 */
	public void setType(String value) {
		setValue(Functions.TYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getType() {
		return getValue(Functions.TYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setMethod(String value) {
		setValue(Functions.METHOD, value);
	}

	/**
	 * An uncommented item
	 */
	public String getMethod() {
		return getValue(Functions.METHOD);
	}

	/**
	 * An uncommented item
	 */
	public void setEffect(String value) {
		setValue(Functions.EFFECT, value);
	}

	/**
	 * An uncommented item
	 */
	public String getEffect() {
		return getValue(Functions.EFFECT);
	}

	/**
	 * An uncommented item
	 */
	public void setParmCount(Short value) {
		setValue(Functions.PARM_COUNT, value);
	}

	/**
	 * An uncommented item
	 */
	public Short getParmCount() {
		return getValue(Functions.PARM_COUNT);
	}

	/**
	 * An uncommented item
	 */
	public void setParmSignature(String value) {
		setValue(Functions.PARM_SIGNATURE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getParmSignature() {
		return getValue(Functions.PARM_SIGNATURE);
	}

	/**
	 * An uncommented item
	 */
	public void setCreateTime(Timestamp value) {
		setValue(Functions.CREATE_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public Timestamp getCreateTime() {
		return getValue(Functions.CREATE_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setQualifier(String value) {
		setValue(Functions.QUALIFIER, value);
	}

	/**
	 * An uncommented item
	 */
	public String getQualifier() {
		return getValue(Functions.QUALIFIER);
	}

	/**
	 * An uncommented item
	 */
	public void setWithFuncAccess(String value) {
		setValue(Functions.WITH_FUNC_ACCESS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getWithFuncAccess() {
		return getValue(Functions.WITH_FUNC_ACCESS);
	}

	/**
	 * An uncommented item
	 */
	public void setTypePreserving(String value) {
		setValue(Functions.TYPE_PRESERVING, value);
	}

	/**
	 * An uncommented item
	 */
	public String getTypePreserving() {
		return getValue(Functions.TYPE_PRESERVING);
	}

	/**
	 * An uncommented item
	 */
	public void setVariant(String value) {
		setValue(Functions.VARIANT, value);
	}

	/**
	 * An uncommented item
	 */
	public String getVariant() {
		return getValue(Functions.VARIANT);
	}

	/**
	 * An uncommented item
	 */
	public void setSideEffects(String value) {
		setValue(Functions.SIDE_EFFECTS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getSideEffects() {
		return getValue(Functions.SIDE_EFFECTS);
	}

	/**
	 * An uncommented item
	 */
	public void setFenced(String value) {
		setValue(Functions.FENCED, value);
	}

	/**
	 * An uncommented item
	 */
	public String getFenced() {
		return getValue(Functions.FENCED);
	}

	/**
	 * An uncommented item
	 */
	public void setNullcall(String value) {
		setValue(Functions.NULLCALL, value);
	}

	/**
	 * An uncommented item
	 */
	public String getNullcall() {
		return getValue(Functions.NULLCALL);
	}

	/**
	 * An uncommented item
	 */
	public void setCastFunction(String value) {
		setValue(Functions.CAST_FUNCTION, value);
	}

	/**
	 * An uncommented item
	 */
	public String getCastFunction() {
		return getValue(Functions.CAST_FUNCTION);
	}

	/**
	 * An uncommented item
	 */
	public void setAssignFunction(String value) {
		setValue(Functions.ASSIGN_FUNCTION, value);
	}

	/**
	 * An uncommented item
	 */
	public String getAssignFunction() {
		return getValue(Functions.ASSIGN_FUNCTION);
	}

	/**
	 * An uncommented item
	 */
	public void setScratchpad(String value) {
		setValue(Functions.SCRATCHPAD, value);
	}

	/**
	 * An uncommented item
	 */
	public String getScratchpad() {
		return getValue(Functions.SCRATCHPAD);
	}

	/**
	 * An uncommented item
	 */
	public void setFinalCall(String value) {
		setValue(Functions.FINAL_CALL, value);
	}

	/**
	 * An uncommented item
	 */
	public String getFinalCall() {
		return getValue(Functions.FINAL_CALL);
	}

	/**
	 * An uncommented item
	 */
	public void setParallelizable(String value) {
		setValue(Functions.PARALLELIZABLE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getParallelizable() {
		return getValue(Functions.PARALLELIZABLE);
	}

	/**
	 * An uncommented item
	 */
	public void setContainsSql(String value) {
		setValue(Functions.CONTAINS_SQL, value);
	}

	/**
	 * An uncommented item
	 */
	public String getContainsSql() {
		return getValue(Functions.CONTAINS_SQL);
	}

	/**
	 * An uncommented item
	 */
	public void setDbinfo(String value) {
		setValue(Functions.DBINFO, value);
	}

	/**
	 * An uncommented item
	 */
	public String getDbinfo() {
		return getValue(Functions.DBINFO);
	}

	/**
	 * An uncommented item
	 */
	public void setResultCols(Short value) {
		setValue(Functions.RESULT_COLS, value);
	}

	/**
	 * An uncommented item
	 */
	public Short getResultCols() {
		return getValue(Functions.RESULT_COLS);
	}

	/**
	 * An uncommented item
	 */
	public void setLanguage(String value) {
		setValue(Functions.LANGUAGE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getLanguage() {
		return getValue(Functions.LANGUAGE);
	}

	/**
	 * An uncommented item
	 */
	public void setImplementation(String value) {
		setValue(Functions.IMPLEMENTATION, value);
	}

	/**
	 * An uncommented item
	 */
	public String getImplementation() {
		return getValue(Functions.IMPLEMENTATION);
	}

	/**
	 * An uncommented item
	 */
	public void setClass_(String value) {
		setValue(Functions.CLASS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getClass_() {
		return getValue(Functions.CLASS);
	}

	/**
	 * An uncommented item
	 */
	public void setJarId(String value) {
		setValue(Functions.JAR_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public String getJarId() {
		return getValue(Functions.JAR_ID);
	}

	/**
	 * An uncommented item
	 */
	public void setParmStyle(String value) {
		setValue(Functions.PARM_STYLE, value);
	}

	/**
	 * An uncommented item
	 */
	public String getParmStyle() {
		return getValue(Functions.PARM_STYLE);
	}

	/**
	 * An uncommented item
	 */
	public void setSourceSchema(String value) {
		setValue(Functions.SOURCE_SCHEMA, value);
	}

	/**
	 * An uncommented item
	 */
	public String getSourceSchema() {
		return getValue(Functions.SOURCE_SCHEMA);
	}

	/**
	 * An uncommented item
	 */
	public void setSourceSpecific(String value) {
		setValue(Functions.SOURCE_SPECIFIC, value);
	}

	/**
	 * An uncommented item
	 */
	public String getSourceSpecific() {
		return getValue(Functions.SOURCE_SPECIFIC);
	}

	/**
	 * An uncommented item
	 */
	public void setIosPerInvoc(Double value) {
		setValue(Functions.IOS_PER_INVOC, value);
	}

	/**
	 * An uncommented item
	 */
	public Double getIosPerInvoc() {
		return getValue(Functions.IOS_PER_INVOC);
	}

	/**
	 * An uncommented item
	 */
	public void setInstsPerInvoc(Double value) {
		setValue(Functions.INSTS_PER_INVOC, value);
	}

	/**
	 * An uncommented item
	 */
	public Double getInstsPerInvoc() {
		return getValue(Functions.INSTS_PER_INVOC);
	}

	/**
	 * An uncommented item
	 */
	public void setIosPerArgbyte(Double value) {
		setValue(Functions.IOS_PER_ARGBYTE, value);
	}

	/**
	 * An uncommented item
	 */
	public Double getIosPerArgbyte() {
		return getValue(Functions.IOS_PER_ARGBYTE);
	}

	/**
	 * An uncommented item
	 */
	public void setInstsPerArgbyte(Double value) {
		setValue(Functions.INSTS_PER_ARGBYTE, value);
	}

	/**
	 * An uncommented item
	 */
	public Double getInstsPerArgbyte() {
		return getValue(Functions.INSTS_PER_ARGBYTE);
	}

	/**
	 * An uncommented item
	 */
	public void setPercentArgbytes(Short value) {
		setValue(Functions.PERCENT_ARGBYTES, value);
	}

	/**
	 * An uncommented item
	 */
	public Short getPercentArgbytes() {
		return getValue(Functions.PERCENT_ARGBYTES);
	}

	/**
	 * An uncommented item
	 */
	public void setInitialIos(Double value) {
		setValue(Functions.INITIAL_IOS, value);
	}

	/**
	 * An uncommented item
	 */
	public Double getInitialIos() {
		return getValue(Functions.INITIAL_IOS);
	}

	/**
	 * An uncommented item
	 */
	public void setInitialInsts(Double value) {
		setValue(Functions.INITIAL_INSTS, value);
	}

	/**
	 * An uncommented item
	 */
	public Double getInitialInsts() {
		return getValue(Functions.INITIAL_INSTS);
	}

	/**
	 * An uncommented item
	 */
	public void setCardinality(Long value) {
		setValue(Functions.CARDINALITY, value);
	}

	/**
	 * An uncommented item
	 */
	public Long getCardinality() {
		return getValue(Functions.CARDINALITY);
	}

	/**
	 * An uncommented item
	 */
	public void setImplemented(String value) {
		setValue(Functions.IMPLEMENTED, value);
	}

	/**
	 * An uncommented item
	 */
	public String getImplemented() {
		return getValue(Functions.IMPLEMENTED);
	}

	/**
	 * An uncommented item
	 */
	public void setSelectivity(Double value) {
		setValue(Functions.SELECTIVITY, value);
	}

	/**
	 * An uncommented item
	 */
	public Double getSelectivity() {
		return getValue(Functions.SELECTIVITY);
	}

	/**
	 * An uncommented item
	 */
	public void setOverriddenFuncid(Integer value) {
		setValue(Functions.OVERRIDDEN_FUNCID, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getOverriddenFuncid() {
		return getValue(Functions.OVERRIDDEN_FUNCID);
	}

	/**
	 * An uncommented item
	 */
	public void setSubjectTypeschema(String value) {
		setValue(Functions.SUBJECT_TYPESCHEMA, value);
	}

	/**
	 * An uncommented item
	 */
	public String getSubjectTypeschema() {
		return getValue(Functions.SUBJECT_TYPESCHEMA);
	}

	/**
	 * An uncommented item
	 */
	public void setSubjectTypename(String value) {
		setValue(Functions.SUBJECT_TYPENAME, value);
	}

	/**
	 * An uncommented item
	 */
	public String getSubjectTypename() {
		return getValue(Functions.SUBJECT_TYPENAME);
	}

	/**
	 * An uncommented item
	 */
	public void setFuncPath(String value) {
		setValue(Functions.FUNC_PATH, value);
	}

	/**
	 * An uncommented item
	 */
	public String getFuncPath() {
		return getValue(Functions.FUNC_PATH);
	}

	/**
	 * An uncommented item
	 */
	public void setBody(String value) {
		setValue(Functions.BODY, value);
	}

	/**
	 * An uncommented item
	 */
	public String getBody() {
		return getValue(Functions.BODY);
	}

	/**
	 * An uncommented item
	 */
	public void setRemarks(String value) {
		setValue(Functions.REMARKS, value);
	}

	/**
	 * An uncommented item
	 */
	public String getRemarks() {
		return getValue(Functions.REMARKS);
	}
	/**
	 * Create a detached FunctionsRecord
	 */
	public FunctionsRecord() {
		super(Functions.FUNCTIONS);
	}
}
