/**
 * This class is generated by jOOQ
 */
package org.jooq.test.db2.generatedclasses.procedures;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.SQLDialect;
import org.jooq.impl.ParameterImpl;
import org.jooq.impl.StoredProcedureImpl;
import org.jooq.test.db2.generatedclasses.Lukas;
import org.jooq.util.db2.DB2DataType;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class PCreateAuthorByName extends StoredProcedureImpl {

	private static final long serialVersionUID = -215104588;


	/**
	 * An uncommented item
	 */
	public static final Parameter<String> FIRST_NAME = new ParameterImpl<String>(SQLDialect.DB2, "FIRST_NAME", DB2DataType.VARCHAR);

	/**
	 * An uncommented item
	 */
	public static final Parameter<String> LAST_NAME = new ParameterImpl<String>(SQLDialect.DB2, "LAST_NAME", DB2DataType.VARCHAR);

	/**
	 * No further instances allowed
	 */
	public PCreateAuthorByName() {
		super(SQLDialect.DB2, "P_CREATE_AUTHOR_BY_NAME", Lukas.LUKAS);

		addInParameter(FIRST_NAME);
		addInParameter(LAST_NAME);
	}

	public void setFirstName(String value) {
		setValue(FIRST_NAME, value);
	}

	public void setLastName(String value) {
		setValue(LAST_NAME, value);
	}
}
