DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS author;

CREATE TABLE author (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL
) ENGINE = InnoDB;

CREATE TABLE book (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	AUTHOR_ID INT NOT NULL,
	TITLE TEXT NOT NULL,
	INDEX (AUTHOR_ID),
	FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID)
) ENGINE = InnoDB;

INSERT INTO author VALUES (NULL, 'George', 'Orwell', '1903-06-25');
INSERT INTO author VALUES (NULL, 'Paulo', 'Coelho', '1947-08-24');

INSERT INTO book VALUES (NULL, 1, '1984');
INSERT INTO book VALUES (NULL, 1, 'Animal Farm');
INSERT INTO book VALUES (NULL, 2, 'O Alquimista');
INSERT INTO book VALUES (NULL, 2, 'Brida');