/**
 * This class is generated by jOOQ
 */
package org.jooq.test.oracle.generatedclasses.tables;


import org.jooq.SQLDialect;
import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.test.oracle.generatedclasses.OdsTest;
import org.jooq.test.oracle.generatedclasses.tables.records.XUnusedRecord;


/**
 * This class is generated by jOOQ.
 *
 * An unused table in the same schema.
 */
public class XUnused extends TableImpl<XUnusedRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The singleton instance of X_UNUSED
	 */
	public static final XUnused X_UNUSED = new XUnused();

	/**
	 * The class holding records for this table
	 */
	private static final Class<XUnusedRecord> RECORD_TYPE = XUnusedRecord.class;

	/**
	 * The class holding records for this table
	 */
	@Override
	public Class<XUnusedRecord> getRecordType() {
		return RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<XUnusedRecord, Integer> ID = new TableFieldImpl<XUnusedRecord, Integer>(SQLDialect.ORACLE, "ID", Integer.class, X_UNUSED);

	/**
	 * An uncommented item
	 */
	public static final TableField<XUnusedRecord, String> NAME = new TableFieldImpl<XUnusedRecord, String>(SQLDialect.ORACLE, "NAME", String.class, X_UNUSED);

	/**
	 * An uncommented item
	 */
	public static final TableField<XUnusedRecord, Integer> ID_REF = new TableFieldImpl<XUnusedRecord, Integer>(SQLDialect.ORACLE, "ID_REF", Integer.class, X_UNUSED);

	/**
	 * An uncommented item
	 */
	public static final TableField<XUnusedRecord, String> NAME_REF = new TableFieldImpl<XUnusedRecord, String>(SQLDialect.ORACLE, "NAME_REF", String.class, X_UNUSED);

	/**
	 * No further instances allowed
	 */
	private XUnused() {
		super(SQLDialect.ORACLE, "X_UNUSED", OdsTest.ODS_TEST);
	}

}
