/**
 * This class is generated by jOOQ
 */
package org.jooq.test.oracle.generatedclasses.tables;

import org.jooq.TableField;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.test.oracle.generatedclasses.OdsTest;
import org.jooq.test.oracle.generatedclasses.tables.records.XUnusedRecord;


/**
 * This class is generated by jOOQ.
 *
 * An unused table in the same schema.
 */
public class XUnused extends TableImpl<XUnusedRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The singleton instance of X_UNUSED
	 */
	public static final XUnused X_UNUSED = new XUnused();

	/**
	 * The class holding records for this table
	 */
	private static final Class<XUnusedRecord> RECORD_TYPE = XUnusedRecord.class;

	/**
	 * The class holding records for this table
	 */
	@Override
	public Class<XUnusedRecord> getRecordType() {
		return RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 *
	 * PRIMARY KEY 'SYS_C0012927'
	 */
	public static final TableField<XUnusedRecord, Integer> ID = new TableFieldImpl<XUnusedRecord, Integer>("ID", Integer.class, X_UNUSED);

	/**
	 * An uncommented item
	 *
	 * PRIMARY KEY 'SYS_C0012927'
	 */
	public static final TableField<XUnusedRecord, String> NAME = new TableFieldImpl<XUnusedRecord, String>("NAME", String.class, X_UNUSED);

	/**
	 * An uncommented item
	 *
	 * FOREIGN KEY 'SYS_C0012927' [ID_REF, NAME_REF] REFERENCES X_UNUSED [ID, NAME]
	 */
	public static final TableField<XUnusedRecord, Integer> ID_REF = new TableFieldImpl<XUnusedRecord, Integer>("ID_REF", Integer.class, X_UNUSED);

	/**
	 * An uncommented item
	 *
	 * FOREIGN KEY 'SYS_C0012927' [ID_REF, NAME_REF] REFERENCES X_UNUSED [ID, NAME]
	 */
	public static final TableField<XUnusedRecord, String> NAME_REF = new TableFieldImpl<XUnusedRecord, String>("NAME_REF", String.class, X_UNUSED);

	/**
	 * No further instances allowed
	 */
	private XUnused() {
		super("X_UNUSED", OdsTest.ODS_TEST);
	}
}
