/**
 * This class is generated by jOOQ
 */
package org.jooq.test.postgres.generatedclasses.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "1.6.8"},
                            comments = "This class is generated by jOOQ")
public class T_959 extends org.jooq.impl.TableImpl<org.jooq.test.postgres.generatedclasses.tables.records.T_959Record> {

	private static final long serialVersionUID = 1098235591;

	/**
	 * The singleton instance of t_959
	 */
	public static final org.jooq.test.postgres.generatedclasses.tables.T_959 T_959 = new org.jooq.test.postgres.generatedclasses.tables.T_959();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<org.jooq.test.postgres.generatedclasses.tables.records.T_959Record> __RECORD_TYPE = org.jooq.test.postgres.generatedclasses.tables.records.T_959Record.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.test.postgres.generatedclasses.tables.records.T_959Record> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * No further instances allowed
	 */
	private T_959() {
		super("t_959", org.jooq.test.postgres.generatedclasses.Public.PUBLIC);
	}
}
