/**
 * This class is generated by jOOQ
 */
package org.jooq.util.derby.sys.tables;


import javax.annotation.Generated;

import org.jooq.TableField;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableFieldImpl;
import org.jooq.impl.TableImpl;
import org.jooq.util.derby.sys.Sys;
import org.jooq.util.derby.sys.tables.records.SysschemasRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public class Sysschemas extends TableImpl<SysschemasRecord> {

	private static final long serialVersionUID = -705239293;

	/**
	 * The singleton instance of SYSSCHEMAS
	 */
	public static final Sysschemas SYSSCHEMAS = new Sysschemas();

	/**
	 * The class holding records for this type
	 */
	private static final Class<SysschemasRecord> __RECORD_TYPE = SysschemasRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SysschemasRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final TableField<SysschemasRecord, String> SCHEMAID = new TableFieldImpl<SysschemasRecord, String>("SCHEMAID", SQLDataType.CHAR, SYSSCHEMAS);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysschemasRecord, String> SCHEMANAME = new TableFieldImpl<SysschemasRecord, String>("SCHEMANAME", SQLDataType.VARCHAR, SYSSCHEMAS);

	/**
	 * An uncommented item
	 */
	public static final TableField<SysschemasRecord, String> AUTHORIZATIONID = new TableFieldImpl<SysschemasRecord, String>("AUTHORIZATIONID", SQLDataType.VARCHAR, SYSSCHEMAS);

	/**
	 * No further instances allowed
	 */
	private Sysschemas() {
		super("SYSSCHEMAS", Sys.SYS);
	}
}
