/**
 * This class is generated by jOOQ
 */
package org.jooq.test.postgres.generatedclasses.enums;


import javax.annotation.Generated;

import org.jooq.EnumType;


/**
 * This class is generated by jOOQ.
 */
@Generated(value    = "http://jooq.sourceforge.net",
           comments = "This class is generated by jOOQ")
public enum UCountry implements EnumType {

	Germany("Germany"),

	England("England"),

	Brazil("Brazil"),

	;

	private final String literal;

	private UCountry(String literal) {
		this.literal = literal;
	}

	@Override
	public String getName() {
		return "u_country";
	}

	@Override
	public String getLiteral() {
		return literal;
	}
}
