/**
 * This class is generated by jOOQ
 */
package org.jooq.util.mysql.mysql.tables.records;

import org.jooq.Result;
import org.jooq.impl.RecordImpl;
import org.jooq.util.mysql.mysql.tables.TimeZoneTransition;


/**
 * This class is generated by jOOQ.
 *
 * Time zone transitions
 */
public class TimeZoneTransitionRecord extends RecordImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * An uncommented item
	 */
	public void setTimeZoneId(Integer value) {
		setValue(TimeZoneTransition.TIME_ZONE_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTimeZoneId() {
		return getValue(TimeZoneTransition.TIME_ZONE_ID);
	}

	/**
	 * An uncommented item
	 */
	public void setTransitionTime(Integer value) {
		setValue(TimeZoneTransition.TRANSITION_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTransitionTime() {
		return getValue(TimeZoneTransition.TRANSITION_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setTransitionTypeId(Integer value) {
		setValue(TimeZoneTransition.TRANSITION_TYPE_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public Integer getTransitionTypeId() {
		return getValue(TimeZoneTransition.TRANSITION_TYPE_ID);
	}

	public TimeZoneTransitionRecord(Result result) {
		super(result);
	}
}
